import { afterEach, describe, expect, it, vi } from "vitest";
import {
    computeFormSummary,
    computePeriodPerformance,
    computePerformance,
    computePerformanceSeries,
    fetchCurrentRating,
    fetchStatsGames,
    groupSessions,
    recentStreak,
    trendPerWeek,
    type StatsGameResult,
    type StatsPerformance,
} from "../statsRating";

// ---------------------------------------------------------------------------
// GOLDEN FIXTURES — generated by executing the ORIGINAL EloGuard engine
// (EloGuard/lib/smart-bracket.js, loaded via require in node) over the exact
// input arrays below. The TS port must reproduce these numbers identically
// (integers exactly, floats to 1e-9). Do not regenerate by hand: the values
// come from computePerformance / computePerformanceSeries / computeSmartBracket
// (mode "blitz", so modeScale 1.0) with nowSec = NOW.
// ---------------------------------------------------------------------------

type FixtureGame = {
    end: number;
    start: number | null;
    rating: number;
    result: StatsGameResult;
    opp: number | null;
};

const NOW = 1_800_000_000;

// Scenario A: mixed win/draw/loss, two games without opponent ratings, three
// sessions separated by multi-hour/day gaps, one session with missing starts.
const SCENARIO_A_GAMES: FixtureGame[] = [
    { end: 1799481600, start: 1799481360, rating: 1500, result: "win", opp: 1480 },
    { end: 1799481900, start: 1799481660, rating: 1508, result: "loss", opp: 1520 },
    { end: 1799482200, start: 1799481960, rating: 1500, result: "draw", opp: 1495 },
    { end: 1799482500, start: 1799482260, rating: 1492, result: "loss", opp: null },
    { end: 1799827200, start: null, rating: 1500, result: "win", opp: 1470 },
    { end: 1799827800, start: null, rating: 1508, result: "win", opp: 1510 },
    { end: 1799828400, start: null, rating: 1500, result: "loss", opp: 1530 },
    { end: 1799829000, start: null, rating: 1500, result: "draw", opp: null },
    { end: 1799992800, start: 1799992560, rating: 1508, result: "win", opp: 1490 },
    { end: 1799993100, start: 1799992860, rating: 1516, result: "win", opp: 1505 },
    { end: 1799993400, start: 1799993160, rating: 1508, result: "loss", opp: 1520 },
    { end: 1799993700, start: 1799993460, rating: 1516, result: "win", opp: 1500 },
];

const SCENARIO_A_EXPECTED = {
    perf: 1586,
    sd: 101.39586909123817,
    ci68: [1485, 1687] as [number, number],
    ci95: [1383, 1789] as [number, number],
    ess: 9.3,
    gamesWithOpp: 10,
    windowStartRating: 1500,
    probAboveCurrent: 0.8,
    sessionSurprise: 1.0215584614353213,
};

// Scenario B: all wins in a single session (prior keeps the estimate finite).
const SCENARIO_B_GAMES: FixtureGame[] = [
    { end: 1799992800, start: 1799992620, rating: 1450, result: "win", opp: 1440 },
    { end: 1799993100, start: 1799992920, rating: 1458, result: "win", opp: 1455 },
    { end: 1799993400, start: 1799993220, rating: 1466, result: "win", opp: 1470 },
    { end: 1799993700, start: 1799993520, rating: 1474, result: "win", opp: 1460 },
    { end: 1799994000, start: 1799993820, rating: 1482, result: "win", opp: 1480 },
    { end: 1799994300, start: 1799994120, rating: 1490, result: "win", opp: 1490 },
];

const SCENARIO_B_EXPECTED = {
    perf: 1715,
    sd: 133.8795988678344,
    ci68: [1581, 1849] as [number, number],
    ci95: [1447, 1983] as [number, number],
    ess: 6,
    gamesWithOpp: 6,
    windowStartRating: 1450,
    probAboveCurrent: 0.98,
    sessionSurprise: 3.1363237713858245,
};

const SCENARIO_B_EXPECTED_NO_CURRENT = {
    ...SCENARIO_B_EXPECTED,
    probAboveCurrent: null,
    sessionSurprise: null,
};

// Scenario C: exactly PERFORMANCE_MIN_GAMES (3) opponent-tagged games.
const SCENARIO_C_GAMES: FixtureGame[] = [
    { end: 1799989200, start: 1799988900, rating: 1520, result: "win", opp: 1500 },
    { end: 1799989600, start: 1799989300, rating: 1512, result: "loss", opp: null },
    { end: 1799990000, start: 1799989700, rating: 1520, result: "win", opp: 1540 },
    { end: 1799990400, start: 1799990100, rating: 1512, result: "loss", opp: 1505 },
];

const SCENARIO_C_EXPECTED = {
    perf: 1575,
    sd: 142.9109989424329,
    ci68: [1432, 1718] as [number, number],
    ci95: [1289, 1861] as [number, number],
    ess: 3,
    gamesWithOpp: 3,
    windowStartRating: 1520,
    probAboveCurrent: 0.65,
    sessionSurprise: 0.4784266669488545,
};

// Scenario D: only two opponent-tagged games among five -> null.
const SCENARIO_D_GAMES: FixtureGame[] = [
    { end: 1799992800, start: 1799992500, rating: 1400, result: "win", opp: 1380 },
    { end: 1799993200, start: null, rating: 1408, result: "win", opp: null },
    { end: 1799993600, start: null, rating: 1400, result: "loss", opp: null },
    { end: 1799994000, start: null, rating: 1408, result: "win", opp: 1420 },
    { end: 1799994400, start: null, rating: 1400, result: "loss", opp: null },
];

// Scenario E: 35 games over ~14 days (5-game clusters every 2 days), 4 missing
// opponent ratings, mixed results — series fixtures for the rolling SWB-TPR.
const SCENARIO_E_GAMES: FixtureGame[] = [
    { end: 1798790400, start: 1798790100, rating: 1508, result: "win", opp: null },
    { end: 1798791000, start: 1798790700, rating: 1516, result: "win", opp: 1477 },
    { end: 1798791600, start: 1798791300, rating: 1508, result: "loss", opp: 1514 },
    { end: 1798792200, start: null, rating: 1508, result: "draw", opp: 1551 },
    { end: 1798792800, start: 1798792500, rating: 1500, result: "loss", opp: 1468 },
    { end: 1798963200, start: 1798962900, rating: 1508, result: "win", opp: 1505 },
    { end: 1798963800, start: 1798963500, rating: 1500, result: "loss", opp: 1542 },
    { end: 1798964400, start: 1798964100, rating: 1508, result: "win", opp: 1459 },
    { end: 1798965000, start: 1798964700, rating: 1516, result: "win", opp: 1496 },
    { end: 1798965600, start: 1798965300, rating: 1508, result: "loss", opp: null },
    { end: 1799136000, start: null, rating: 1516, result: "win", opp: 1450 },
    { end: 1799136600, start: 1799136300, rating: 1524, result: "win", opp: 1487 },
    { end: 1799137200, start: 1799136900, rating: 1516, result: "loss", opp: 1524 },
    { end: 1799137800, start: 1799137500, rating: 1516, result: "draw", opp: 1441 },
    { end: 1799138400, start: 1799138100, rating: 1508, result: "loss", opp: 1478 },
    { end: 1799308800, start: 1799308500, rating: 1516, result: "win", opp: 1515 },
    { end: 1799309400, start: 1799309100, rating: 1508, result: "loss", opp: 1552 },
    { end: 1799310000, start: null, rating: 1516, result: "win", opp: 1469 },
    { end: 1799310600, start: 1799310300, rating: 1524, result: "win", opp: null },
    { end: 1799311200, start: 1799310900, rating: 1516, result: "loss", opp: 1543 },
    { end: 1799481600, start: 1799481300, rating: 1524, result: "win", opp: 1460 },
    { end: 1799482200, start: 1799481900, rating: 1532, result: "win", opp: 1497 },
    { end: 1799482800, start: 1799482500, rating: 1524, result: "loss", opp: 1534 },
    { end: 1799483400, start: 1799483100, rating: 1524, result: "draw", opp: 1451 },
    { end: 1799484000, start: null, rating: 1516, result: "loss", opp: 1488 },
    { end: 1799654400, start: 1799654100, rating: 1524, result: "win", opp: 1525 },
    { end: 1799655000, start: 1799654700, rating: 1516, result: "loss", opp: 1442 },
    { end: 1799655600, start: 1799655300, rating: 1524, result: "win", opp: null },
    { end: 1799656200, start: 1799655900, rating: 1532, result: "win", opp: 1516 },
    { end: 1799656800, start: 1799656500, rating: 1524, result: "loss", opp: 1553 },
    { end: 1799827200, start: 1799826900, rating: 1532, result: "win", opp: 1470 },
    { end: 1799827800, start: null, rating: 1540, result: "win", opp: 1507 },
    { end: 1799828400, start: 1799828100, rating: 1532, result: "loss", opp: 1544 },
    { end: 1799829000, start: 1799828700, rating: 1532, result: "draw", opp: 1461 },
    { end: 1799829600, start: 1799829300, rating: 1524, result: "loss", opp: 1498 },
];

const SCENARIO_E_SERIES_DEFAULT = [
    { end: 1798792200, perf: 1511, sd: 141.90656891350767 },
    { end: 1798792800, perf: 1455, sd: 132.17193059645498 },
    { end: 1798963200, perf: 1508, sd: 124.96221551119338 },
    { end: 1798963800, perf: 1472, sd: 118.1092328866123 },
    { end: 1798964400, perf: 1506, sd: 111.55776350909026 },
    { end: 1798965000, perf: 1538, sd: 106.63197397957651 },
    { end: 1798965600, perf: 1538, sd: 106.6406772273583 },
    { end: 1799136000, perf: 1561, sd: 105.17162086103625 },
    { end: 1799136600, perf: 1585, sd: 101.95539943022712 },
    { end: 1799137200, perf: 1553, sd: 96.60498190821363 },
    { end: 1799137800, perf: 1545, sd: 93.14924364233474 },
    { end: 1799138400, perf: 1517, sd: 89.4524338964739 },
    { end: 1799308800, perf: 1540, sd: 89.21062066302147 },
    { end: 1799309400, perf: 1519, sd: 86.04542520430924 },
    { end: 1799310000, perf: 1536, sd: 83.88977193416287 },
    { end: 1799310600, perf: 1536, sd: 83.89766895782112 },
    { end: 1799311200, perf: 1518, sd: 81.27038429552881 },
    { end: 1799481600, perf: 1535, sd: 81.52850334064688 },
    { end: 1799482200, perf: 1538, sd: 81.0734683898648 },
    { end: 1799482800, perf: 1535, sd: 80.49281584370134 },
    { end: 1799483400, perf: 1528, sd: 79.98793111292277 },
    { end: 1799484000, perf: 1526, sd: 79.44121942708931 },
    { end: 1799654400, perf: 1529, sd: 81.17865646989954 },
    { end: 1799655000, perf: 1521, sd: 80.64882602574716 },
    { end: 1799655600, perf: 1510, sd: 82.17621058731983 },
    { end: 1799656200, perf: 1514, sd: 81.69664046861446 },
    { end: 1799656800, perf: 1499, sd: 79.47661361721677 },
    { end: 1799827200, perf: 1506, sd: 81.15594116487625 },
    { end: 1799827800, perf: 1510, sd: 80.66988960473404 },
    { end: 1799828400, perf: 1507, sd: 80.18174847409465 },
    { end: 1799829000, perf: 1506, sd: 79.674679562216 },
    { end: 1799829600, perf: 1503, sd: 79.1874790678517 },
];

const SCENARIO_E_SERIES_WINDOW_5 = [
    { end: 1798792200, perf: 1511, sd: 141.90656891350767 },
    { end: 1798792800, perf: 1455, sd: 132.17193059645498 },
    { end: 1798963200, perf: 1511, sd: 124.97460463130037 },
    { end: 1798963800, perf: 1428, sd: 126.81195071755747 },
    { end: 1798964400, perf: 1509, sd: 124.1315170018209 },
    { end: 1798965000, perf: 1543, sd: 124.2187952402795 },
    { end: 1798965600, perf: 1605, sd: 134.66855074882255 },
    { end: 1799136000, perf: 1593, sd: 136.71270374341182 },
    { end: 1799136600, perf: 1699, sd: 146.5437833887299 },
    { end: 1799137200, perf: 1600, sd: 135.60363298867696 },
    { end: 1799137800, perf: 1540, sd: 132.73273667065612 },
    { end: 1799138400, perf: 1491, sd: 123.06249030478736 },
    { end: 1799308800, perf: 1506, sd: 125.03927513937391 },
    { end: 1799309400, perf: 1423, sd: 126.56281613660352 },
    { end: 1799310000, perf: 1504, sd: 124.20468912450734 },
    { end: 1799310600, perf: 1509, sd: 132.10582895161852 },
    { end: 1799311200, perf: 1518, sd: 131.4933414433642 },
    { end: 1799481600, perf: 1510, sd: 133.5064760864768 },
    { end: 1799482200, perf: 1606, sd: 136.48949618360476 },
    { end: 1799482800, perf: 1518, sd: 132.11692803283586 },
    { end: 1799483400, perf: 1507, sd: 123.66997798809223 },
    { end: 1799484000, perf: 1500, sd: 123.05554572841396 },
    { end: 1799654400, perf: 1515, sd: 125.03161954318784 },
    { end: 1799655000, perf: 1418, sd: 126.12122308356133 },
    { end: 1799655600, perf: 1450, sd: 132.91166725901363 },
    { end: 1799656200, perf: 1506, sd: 132.1385848208545 },
    { end: 1799656800, perf: 1516, sd: 131.69323105251516 },
    { end: 1799827200, perf: 1508, sd: 133.55663032565448 },
    { end: 1799827800, perf: 1620, sd: 136.11378209442844 },
    { end: 1799828400, perf: 1568, sd: 124.73071236400142 },
    { end: 1799829000, perf: 1516, sd: 123.6653614827817 },
    { end: 1799829600, perf: 1510, sd: 123.04895666247668 },
];

// Form F1: recent 3-loss streak against +400 opponents — session surprise stays
// above -0.8, so the streak tilt is SUPPRESSED (original stats.tilt === false).
const FORM_F1_GAMES: FixtureGame[] = [
    { end: 1799740800, start: 1799740560, rating: 1508, result: "win", opp: 1500 },
    { end: 1799741100, start: 1799740860, rating: 1500, result: "loss", opp: 1505 },
    { end: 1799741400, start: 1799741160, rating: 1508, result: "win", opp: 1495 },
    { end: 1799741700, start: 1799741460, rating: 1500, result: "loss", opp: 1500 },
    { end: 1799742000, start: 1799741760, rating: 1508, result: "win", opp: 1502 },
    { end: 1799742300, start: 1799742060, rating: 1500, result: "loss", opp: 1498 },
    { end: 1799996700, start: 1799996460, rating: 1508, result: "win", opp: 1900 },
    { end: 1799997000, start: 1799996760, rating: 1516, result: "win", opp: 1900 },
    { end: 1799997300, start: 1799997060, rating: 1524, result: "win", opp: 1900 },
    { end: 1799997600, start: 1799997360, rating: 1516, result: "loss", opp: 1900 },
    { end: 1799997900, start: 1799997660, rating: 1508, result: "loss", opp: 1900 },
    { end: 1799998200, start: 1799997960, rating: 1500, result: "loss", opp: 1900 },
];

const FORM_F1_EXPECTED = {
    slopePerWeek: 18.9,
    streak: { type: "loss", len: 3 } as { type: StatsGameResult; len: number } | null,
    sessions: 2,
    net10: 0,
    tilt: false,
    avgLossPts: 8,
    avgWinPts: 8,
    latestSessionNet: -8,
    latestSessionGames: 6,
};

// Form F2: no streak/net tilt, but quietly losing to -300 opponents pushes the
// session surprise to <= -1.5 with 6 valid opponents — tilt fires via surprise.
const FORM_F2_GAMES: FixtureGame[] = [
    { end: 1799827200, start: 1799826960, rating: 1508, result: "win", opp: 1500 },
    { end: 1799827500, start: 1799827260, rating: 1500, result: "loss", opp: 1505 },
    { end: 1799827800, start: 1799827560, rating: 1508, result: "win", opp: 1495 },
    { end: 1799828100, start: 1799827860, rating: 1500, result: "loss", opp: 1500 },
    { end: 1799828400, start: 1799828160, rating: 1508, result: "win", opp: 1502 },
    { end: 1799828700, start: 1799828460, rating: 1500, result: "loss", opp: 1498 },
    { end: 1799997600, start: 1799997360, rating: 1492, result: "loss", opp: 1200 },
    { end: 1799997900, start: 1799997660, rating: 1484, result: "loss", opp: 1200 },
    { end: 1799998200, start: 1799997960, rating: 1492, result: "win", opp: 1200 },
    { end: 1799998500, start: 1799998260, rating: 1484, result: "loss", opp: 1200 },
    { end: 1799998800, start: 1799998560, rating: 1476, result: "loss", opp: 1200 },
    { end: 1799999100, start: 1799998860, rating: 1484, result: "win", opp: 1200 },
];

const FORM_F2_EXPECTED = {
    slopePerWeek: -66.4,
    streak: { type: "win", len: 1 } as { type: StatsGameResult; len: number } | null,
    sessions: 2,
    net10: -16,
    tilt: true,
    avgLossPts: 8,
    avgWinPts: 8,
    latestSessionNet: -8,
    latestSessionGames: 6,
};

// Form F3: heavy losing session (net -50 <= -2.5 * avgLossPts) — net tilt fires
// and surprise suppression does not apply.
const FORM_F3_GAMES: FixtureGame[] = [
    { end: 1799870400, start: 1799870160, rating: 1510, result: "win", opp: 1500 },
    { end: 1799870700, start: 1799870460, rating: 1520, result: "win", opp: 1495 },
    { end: 1799871000, start: 1799870760, rating: 1510, result: "loss", opp: 1505 },
    { end: 1799871300, start: 1799871060, rating: 1520, result: "win", opp: 1500 },
    { end: 1799871600, start: 1799871360, rating: 1510, result: "loss", opp: 1498 },
    { end: 1799997900, start: 1799997660, rating: 1490, result: "loss", opp: 1505 },
    { end: 1799998200, start: 1799997960, rating: 1480, result: "loss", opp: 1495 },
    { end: 1799998500, start: 1799998260, rating: 1470, result: "loss", opp: 1500 },
    { end: 1799998800, start: 1799998560, rating: 1460, result: "loss", opp: 1490 },
    { end: 1799999100, start: 1799998860, rating: 1450, result: "loss", opp: 1485 },
    { end: 1799999400, start: 1799999160, rating: 1440, result: "loss", opp: 1500 },
];

const FORM_F3_EXPECTED = {
    slopePerWeek: -232.9,
    streak: { type: "loss", len: 7 } as { type: StatsGameResult; len: number } | null,
    sessions: 2,
    net10: -70,
    tilt: true,
    avgLossPts: 11.25,
    avgWinPts: 8,
    latestSessionNet: -50,
    latestSessionGames: 6,
};

// Form F4: losing session that ended > 12h before nowSec — stale, no tilt.
const FORM_F4_GAMES: FixtureGame[] = [
    { end: 1799654400, start: 1799654160, rating: 1508, result: "win", opp: 1500 },
    { end: 1799654700, start: 1799654460, rating: 1516, result: "win", opp: 1495 },
    { end: 1799655000, start: 1799654760, rating: 1508, result: "loss", opp: 1505 },
    { end: 1799655300, start: 1799655060, rating: 1516, result: "win", opp: 1500 },
    { end: 1799655600, start: 1799655360, rating: 1508, result: "loss", opp: 1498 },
    { end: 1799655900, start: 1799655660, rating: 1516, result: "win", opp: 1502 },
    { end: 1799656200, start: 1799655960, rating: 1508, result: "loss", opp: 1500 },
    { end: 1799948700, start: 1799948460, rating: 1500, result: "loss", opp: 1505 },
    { end: 1799949000, start: 1799948760, rating: 1492, result: "loss", opp: 1500 },
    { end: 1799949300, start: 1799949060, rating: 1484, result: "loss", opp: 1495 },
    { end: 1799949600, start: 1799949360, rating: 1476, result: "loss", opp: 1490 },
];

const FORM_F4_EXPECTED = {
    slopePerWeek: -48.3,
    streak: { type: "loss", len: 5 } as { type: StatsGameResult; len: number } | null,
    sessions: 2,
    net10: -32,
    tilt: false,
    avgLossPts: 8,
    avgWinPts: 8,
    latestSessionNet: -24,
    latestSessionGames: 4,
};

type PerformanceExpectation = {
    perf: number;
    sd: number;
    ci68: [number, number];
    ci95: [number, number];
    ess: number;
    gamesWithOpp: number;
    windowStartRating: number;
    probAboveCurrent: number | null;
    sessionSurprise: number | null;
};

// Floats are compared to 1e-9 by canonicalizing both sides; the port performs
// the exact same double operations, so the rounded values must be identical.
function round9(value: number) {
    return Math.round(value * 1e9) / 1e9;
}

function canonicalPerformance(value: PerformanceExpectation): PerformanceExpectation {
    return {
        ...value,
        sd: round9(value.sd),
        probAboveCurrent: value.probAboveCurrent === null ? null : round9(value.probAboveCurrent),
        sessionSurprise: value.sessionSurprise === null ? null : round9(value.sessionSurprise),
    };
}

function expectPerformance(actual: StatsPerformance | null, expected: PerformanceExpectation) {
    expect(actual).not.toBeNull();
    expect(canonicalPerformance(actual as StatsPerformance)).toEqual(
        canonicalPerformance(expected),
    );
}

afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
});

describe("computePerformance golden fidelity vs original smart-bracket.js", () => {
    it("matches the original on mixed results with draws, missing opponents and session gaps", () => {
        const actual = computePerformance(SCENARIO_A_GAMES, { currentRating: 1500, nowSec: NOW });
        expectPerformance(actual, SCENARIO_A_EXPECTED);
    });

    it("matches the original on an all-wins run (prior keeps the estimate finite)", () => {
        const actual = computePerformance(SCENARIO_B_GAMES, { currentRating: 1450, nowSec: NOW });
        expectPerformance(actual, SCENARIO_B_EXPECTED);
    });

    it("nulls probAboveCurrent and sessionSurprise without a current rating", () => {
        const actual = computePerformance(SCENARIO_B_GAMES, { currentRating: null, nowSec: NOW });
        expectPerformance(actual, SCENARIO_B_EXPECTED_NO_CURRENT);
    });

    it("matches the original at the exactly-3-opponent-tagged-games boundary", () => {
        const actual = computePerformance(SCENARIO_C_GAMES, { currentRating: 1520, nowSec: NOW });
        expectPerformance(actual, SCENARIO_C_EXPECTED);
    });

    it("returns null with fewer than 3 opponent-tagged games", () => {
        expect(
            computePerformance(SCENARIO_D_GAMES, { currentRating: 1400, nowSec: NOW }),
        ).toBeNull();
        expect(computePerformance([], { currentRating: 1400, nowSec: NOW })).toBeNull();
    });
});

describe("computePerformanceSeries golden fidelity vs original smart-bracket.js", () => {
    it("matches the original 35-game rolling series (default windowSize 20)", () => {
        const series = computePerformanceSeries(SCENARIO_E_GAMES);
        expect(series.length).toBe(SCENARIO_E_SERIES_DEFAULT.length);
        for (let i = 0; i < series.length; i += 1) {
            expect(series[i].end).toBe(SCENARIO_E_SERIES_DEFAULT[i].end);
            expect(series[i].perf).toBe(SCENARIO_E_SERIES_DEFAULT[i].perf);
            expect(series[i].sd).toBeCloseTo(SCENARIO_E_SERIES_DEFAULT[i].sd, 9);
        }
    });

    it("matches the original with an explicit windowSize of 5", () => {
        const series = computePerformanceSeries(SCENARIO_E_GAMES, { windowSize: 5 });
        expect(series.length).toBe(SCENARIO_E_SERIES_WINDOW_5.length);
        for (let i = 0; i < series.length; i += 1) {
            expect(series[i].end).toBe(SCENARIO_E_SERIES_WINDOW_5[i].end);
            expect(series[i].perf).toBe(SCENARIO_E_SERIES_WINDOW_5[i].perf);
            expect(series[i].sd).toBeCloseTo(SCENARIO_E_SERIES_WINDOW_5[i].sd, 9);
        }
    });
});

describe("computePeriodPerformance", () => {
    it("uses every game in the selected period instead of the latest rolling chart point", () => {
        const games = Array.from({ length: 30 }, (_, index) => ({
            end: NOW - (29 - index) * 12 * 3600,
            start: null,
            rated: true,
            rating: 1500,
            opp: index < 15 ? 1900 : 1100,
            result: (index < 15 ? "win" : "loss") as StatsGameResult,
        }));

        const performance = computePeriodPerformance(games, {
            currentRating: 1500,
            nowSec: NOW,
            windowStart: games[0].end,
            windowEnd: NOW,
        });
        const latestRollingPoint = computePerformanceSeries(games, { windowSize: 20 }).at(-1);

        expect(performance?.gamesWithOpp).toBe(30);
        expect(performance?.perf).toBe(1342);
        expect(latestRollingPoint?.perf).toBe(1048);
        expect(performance?.perf).not.toBe(latestRollingPoint?.perf);
    });
});

describe("computeFormSummary golden fidelity vs original computeSmartBracket", () => {
    it("suppresses streak tilt when the loss streak came against much stronger opponents", () => {
        const actual = computeFormSummary(FORM_F1_GAMES, { currentRating: 1500, nowSec: NOW });
        expect(actual).toEqual(FORM_F1_EXPECTED);
    });

    it("fires tilt via session surprise when quietly losing games it would usually win", () => {
        const actual = computeFormSummary(FORM_F2_GAMES, { currentRating: 1500, nowSec: NOW });
        expect(actual).toEqual(FORM_F2_EXPECTED);
    });

    it("fires tilt from the session net without surprise suppression", () => {
        const actual = computeFormSummary(FORM_F3_GAMES, { currentRating: 1500, nowSec: NOW });
        expect(actual).toEqual(FORM_F3_EXPECTED);
    });

    it("does not tilt when the losing session is older than 12 hours", () => {
        const actual = computeFormSummary(FORM_F4_GAMES, { currentRating: 1500, nowSec: NOW });
        expect(actual).toEqual(FORM_F4_EXPECTED);
    });

    it("only refines tilt through the performance layer when opponents are known", () => {
        const streakLosses: FixtureGame[] = [
            { end: NOW - 2100, start: NOW - 2340, rating: 1508, result: "win", opp: 1900 },
            { end: NOW - 1800, start: NOW - 2040, rating: 1516, result: "win", opp: 1900 },
            { end: NOW - 1500, start: NOW - 1740, rating: 1524, result: "win", opp: 1900 },
            { end: NOW - 1200, start: NOW - 1440, rating: 1516, result: "loss", opp: 1900 },
            { end: NOW - 900, start: NOW - 1140, rating: 1508, result: "loss", opp: 1900 },
            { end: NOW - 600, start: NOW - 840, rating: 1500, result: "loss", opp: 1900 },
        ];
        // Session surprise stays positive -> the loss streak is not tilt.
        const refined = computeFormSummary(streakLosses, { currentRating: 1500, nowSec: NOW });
        expect(refined.tilt).toBe(false);
        // Without opponent ratings there is no performance layer, so the raw
        // streak rule stands.
        const noOpps = streakLosses.map((game) => ({ ...game, opp: null }));
        const raw = computeFormSummary(noOpps, { currentRating: 1500, nowSec: NOW });
        expect(raw.tilt).toBe(true);
    });
});

describe("session and trend helpers", () => {
    it("groups sessions with the 3600s gap on start when present, end otherwise", () => {
        expect(groupSessions(SCENARIO_A_GAMES).map((session) => session.length)).toEqual([4, 4, 4]);
        // start-based gap keeps games together even when ends are far apart...
        const games = [
            { end: 1000, start: null },
            { end: 90000, start: 1500 },
            // ...and a null start falls back to the end-to-end gap.
            { end: 95000, start: null },
        ];
        expect(groupSessions(games).map((session) => session.length)).toEqual([2, 1]);
        expect(groupSessions([])).toEqual([]);
    });

    it("computes recent streaks and handles empty input", () => {
        expect(recentStreak([])).toBeNull();
        expect(
            recentStreak([{ result: "win" }, { result: "loss" }, { result: "loss" }] as {
                result: StatsGameResult;
            }[]),
        ).toEqual({ type: "loss", len: 2 });
    });

    it("returns 0 trend for fewer than 5 games or a degenerate time axis", () => {
        expect(trendPerWeek(SCENARIO_C_GAMES)).toBe(0);
        expect(
            trendPerWeek([
                { end: NOW, rating: 1500 },
                { end: NOW, rating: 1510 },
                { end: NOW, rating: 1520 },
                { end: NOW, rating: 1530 },
                { end: NOW, rating: 1540 },
            ]),
        ).toBe(0);
    });
});

// ---------------------------------------------------------------------------
// Fetch normalization
// ---------------------------------------------------------------------------

type MockResponse = { json?: unknown; text?: string; status?: number };

function getRequestHeaders(init: RequestInit | undefined) {
    return (init?.headers ?? {}) as Record<string, string>;
}

function stubFetch(matcher: (url: string) => MockResponse | null) {
    const requests: { url: string; init: RequestInit | undefined }[] = [];
    const mock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
        const url = String(input);
        requests.push({ url, init });
        const route = matcher(url);
        if (!route) {
            return { ok: false, status: 404, json: async () => ({}), text: async () => "" };
        }
        const status = route.status ?? 200;
        return {
            ok: status >= 200 && status < 300,
            status,
            json: async () => route.json,
            text: async () => route.text ?? "",
        };
    });
    vi.stubGlobal("fetch", mock);
    return { mock, requests };
}

const CHESSCOM_PGN = [
    '[Event "Live Chess"]',
    '[Site "Chess.com"]',
    '[Date "2026.07.20"]',
    '[White "StatsGuy"]',
    '[Black "Rival1"]',
    '[Result "1-0"]',
    '[ECO "B01"]',
    '[ECOUrl "https://www.chess.com/openings/Scandinavian-Defense-Mieses-Kotroc-Variation"]',
    '[UTCDate "2026.07.20"]',
    '[UTCTime "18:05:00"]',
    "",
    "1. e4 {[%clk 0:03:00]} d5 {[%clk 0:02:58]} 2. exd5 {[%clk 0:02:59]} Qxd5 {[%clk 0:02:55]} 1-0",
].join("\n");

function buildChessComArchive(nowSec: number) {
    return {
        games: [
            {
                url: "https://www.chess.com/game/live/7",
                end_time: nowSec - 12000,
                time_class: "blitz",
                time_control: "180",
                rules: "chess",
                rated: true,
                white: { username: "StatsGuy", rating: 1490, result: "checkmated" },
                black: { username: "Rival4", result: "win" },
            },
            {
                url: "https://www.chess.com/game/live/1",
                pgn: CHESSCOM_PGN,
                end_time: nowSec - 9000,
                time_class: "blitz",
                time_control: "180",
                rules: "chess",
                rated: true,
                white: { username: "StatsGuy", rating: 1512, result: "win" },
                black: { username: "Rival1", rating: 1498, result: "resigned" },
            },
            {
                url: "https://www.chess.com/game/live/2",
                end_time: nowSec - 6000,
                time_class: "blitz",
                time_control: "180+2",
                rules: "chess",
                rated: true,
                white: { username: "Rival2", rating: 1510, result: "win" },
                black: { username: "StatsGuy", rating: 1500, result: "timeout" },
            },
            {
                url: "https://www.chess.com/game/live/3",
                end_time: nowSec - 3000,
                time_class: "blitz",
                time_control: "180",
                rules: "chess",
                rated: false,
                white: { username: "StatsGuy", rating: 1505, result: "repetition" },
                black: { username: "Rival3", rating: 1507, result: "repetition" },
            },
            {
                url: "https://www.chess.com/game/daily/4",
                end_time: nowSec - 1500,
                time_class: "daily",
                time_control: "1/86400",
                rules: "chess",
                rated: true,
                white: { username: "StatsGuy", rating: 1400, result: "win" },
                black: { username: "DailyFoe", rating: 1380, result: "abandoned" },
            },
            {
                url: "https://www.chess.com/game/live/5",
                end_time: nowSec - 1000,
                time_class: "blitz",
                time_control: "180",
                rules: "bughouse",
                rated: true,
                white: { username: "StatsGuy", rating: 1300, result: "win" },
                black: { username: "BugFoe", rating: 1310, result: "resigned" },
            },
            {
                url: "https://www.chess.com/game/live/6",
                end_time: nowSec - 500,
                time_class: "rapid",
                time_control: "600+5",
                rules: "chess",
                rated: true,
                white: { username: "StatsGuy", rating: 1600, result: "win" },
                black: { username: "RapidFoe", rating: 1590, result: "resigned" },
            },
        ],
    };
}

function stubChessComFetch(nowSec: number) {
    const archivesUrl = "https://api.chess.com/pub/player/StatsGuy/games/archives";
    const monthUrl = "https://api.chess.com/pub/player/statsguy/games/2026/07";
    const olderMonthUrl = "https://api.chess.com/pub/player/statsguy/games/2026/06";
    return stubFetch((url) => {
        if (url === archivesUrl) return { json: { archives: [olderMonthUrl, monthUrl] } };
        if (url === monthUrl) return { json: buildChessComArchive(nowSec) };
        if (url === olderMonthUrl) return { json: { games: [] } };
        return null;
    });
}

describe("fetchStatsGames chess.com normalization", () => {
    it("normalizes archive games with terminations, time controls and openings", async () => {
        const nowSec = Math.floor(Date.now() / 1000);
        stubChessComFetch(nowSec);

        const games = await fetchStatsGames({
            source: "chesscom",
            username: "StatsGuy",
            timeClass: "blitz",
            ratedFilter: "both",
            maxGames: 100,
            maxDays: 30,
            monthsCap: 2,
        });

        expect(games.map((game) => game.termination)).toEqual([
            "checkmate",
            "resign",
            "timeout",
            "draw",
        ]);
        expect(games.map((game) => game.result)).toEqual(["loss", "win", "loss", "draw"]);
        expect(games.map((game) => game.end)).toEqual([
            nowSec - 12000,
            nowSec - 9000,
            nowSec - 6000,
            nowSec - 3000,
        ]);

        const win = games[1];
        expect(win.source).toBe("chesscom");
        expect(win.id).toBe("https://www.chess.com/game/live/1");
        expect(win.url).toBe("https://www.chess.com/game/live/1");
        expect(win.start).toBe(Date.UTC(2026, 6, 20, 18, 5, 0) / 1000);
        expect(win.rating).toBe(1512);
        expect(win.opp).toBe(1498);
        expect(win.oppName).toBe("Rival1");
        expect(win.rated).toBe(true);
        expect(win.color).toBe("w");
        expect(win.timeClass).toBe("blitz");
        expect(win.timeControl).toEqual({ base: 180, inc: 0 });
        expect(win.eco).toBe("B01");
        expect(win.openingName).toBe("Scandinavian Defense Mieses Kotroc Variation");
        expect(win.pgn).toBe(CHESSCOM_PGN);

        const timeoutLoss = games[2];
        expect(timeoutLoss.color).toBe("b");
        expect(timeoutLoss.timeControl).toEqual({ base: 180, inc: 2 });
        expect(timeoutLoss.start).toBeNull();
        expect(timeoutLoss.eco).toBeNull();
        expect(timeoutLoss.pgn).toBeNull();

        // Missing opponent rating stays null.
        expect(games[0].opp).toBeNull();
        expect(games[0].oppName).toBe("Rival4");
        // Casual game kept under "both".
        expect(games[3].rated).toBe(false);
    });

    it("applies the rated/casual filters", async () => {
        const nowSec = Math.floor(Date.now() / 1000);
        stubChessComFetch(nowSec);
        const rated = await fetchStatsGames({
            source: "chesscom",
            username: "StatsGuy",
            timeClass: "blitz",
            ratedFilter: "rated",
            maxGames: 100,
            maxDays: 30,
            monthsCap: 2,
        });
        expect(rated.map((game) => game.rated)).toEqual([true, true, true]);

        stubChessComFetch(nowSec);
        const casual = await fetchStatsGames({
            source: "chesscom",
            username: "StatsGuy",
            timeClass: "blitz",
            ratedFilter: "casual",
            maxGames: 100,
            maxDays: 30,
            monthsCap: 2,
        });
        expect(casual.map((game) => game.url)).toEqual(["https://www.chess.com/game/live/3"]);
    });

    it("normalizes daily games with the 1/86400 time control", async () => {
        const nowSec = Math.floor(Date.now() / 1000);
        stubChessComFetch(nowSec);
        const games = await fetchStatsGames({
            source: "chesscom",
            username: "StatsGuy",
            timeClass: "daily",
            ratedFilter: "both",
            maxGames: 100,
            maxDays: 30,
            monthsCap: 2,
        });
        expect(games).toHaveLength(1);
        expect(games[0].timeClass).toBe("daily");
        expect(games[0].timeControl).toEqual({ base: 86400, inc: 0 });
        // I won because the opponent abandoned.
        expect(games[0].termination).toBe("abandon");
        expect(games[0].result).toBe("win");
    });

    it("keeps only the most recent maxGames", async () => {
        const nowSec = Math.floor(Date.now() / 1000);
        stubChessComFetch(nowSec);
        const games = await fetchStatsGames({
            source: "chesscom",
            username: "StatsGuy",
            timeClass: "blitz",
            ratedFilter: "both",
            maxGames: 2,
            maxDays: 30,
            monthsCap: 2,
        });
        expect(games.map((game) => game.end)).toEqual([nowSec - 6000, nowSec - 3000]);
    });
});

function buildLichessNdjson(nowMs: number) {
    const lines = [
        {
            id: "aaaa1111",
            rated: true,
            variant: "standard",
            speed: "blitz",
            createdAt: nowMs - 3_600_000,
            lastMoveAt: nowMs - 3_540_000,
            status: "mate",
            winner: "white",
            players: {
                white: { user: { name: "LichUser" }, rating: 1500, ratingDiff: 8 },
                black: { user: { name: "Nemesis" }, rating: 1520, ratingDiff: -7 },
            },
            opening: { eco: "B90", name: "Sicilian Defense: Najdorf Variation" },
            clock: { initial: 180, increment: 2 },
            pgn: '[Event "Rated blitz game"]\n\n1. e4 { [%eval 0.2] [%clk 0:03:00] } c5 1-0',
        },
        {
            id: "bbbb2222",
            rated: false,
            variant: "standard",
            speed: "blitz",
            createdAt: nowMs - 3_000_000,
            lastMoveAt: nowMs - 2_940_000,
            status: "resign",
            winner: "black",
            players: {
                white: { user: { name: "LichUser" }, rating: 1495 },
                black: { user: { name: "CasualFoe" }, rating: 1480 },
            },
            clock: { initial: 180, increment: 0 },
        },
        {
            id: "cccc3333",
            rated: true,
            variant: "standard",
            speed: "blitz",
            createdAt: nowMs - 2_400_000,
            lastMoveAt: nowMs - 2_340_000,
            status: "stalemate",
            players: {
                white: { user: { name: "OtherGuy" }, rating: 1510, ratingDiff: 0 },
                black: { user: { name: "LichUser" }, rating: 1502, ratingDiff: 1 },
            },
            clock: { initial: 180, increment: 2 },
        },
        {
            id: "dddd4444",
            rated: true,
            variant: "standard",
            speed: "blitz",
            createdAt: nowMs - 1_800_000,
            lastMoveAt: nowMs - 1_740_000,
            status: "outoftime",
            winner: "black",
            players: {
                white: { user: { name: "LichUser" }, rating: 1503, ratingDiff: -9 },
                black: { user: { name: "Speedster" }, rating: 1490, ratingDiff: 10 },
            },
            clock: { initial: 180, increment: 2 },
        },
        {
            id: "eeee5555",
            rated: false,
            variant: "standard",
            speed: "blitz",
            createdAt: nowMs - 1_200_000,
            lastMoveAt: nowMs - 1_140_000,
            status: "aborted",
            players: {
                white: { user: { name: "LichUser" }, rating: 1494 },
                black: { user: { name: "Quitter" }, rating: 1505 },
            },
            clock: { initial: 180, increment: 2 },
        },
        {
            id: "ffff6666",
            rated: true,
            variant: "crazyhouse",
            speed: "blitz",
            createdAt: nowMs - 900_000,
            lastMoveAt: nowMs - 840_000,
            status: "mate",
            winner: "white",
            players: {
                white: { user: { name: "LichUser" }, rating: 1700, ratingDiff: 5 },
                black: { user: { name: "ZhFoe" }, rating: 1690, ratingDiff: -5 },
            },
            clock: { initial: 180, increment: 2 },
        },
    ];
    // The API streams newest-first (sort=dateDesc).
    return lines
        .slice()
        .reverse()
        .map((line) => JSON.stringify(line))
        .join("\n");
}

function stubLichessFetch(nowMs: number) {
    return stubFetch((url) => {
        if (url.startsWith("https://lichess.org/api/games/user/LichUser")) {
            return { text: buildLichessNdjson(nowMs) };
        }
        return null;
    });
}

describe("fetchStatsGames lichess normalization", () => {
    it("normalizes ndjson games with ratingDiff and status variants", async () => {
        const nowMs = Date.now();
        const { requests } = stubLichessFetch(nowMs);

        const games = await fetchStatsGames({
            source: "lichess",
            username: "LichUser",
            timeClass: "blitz",
            ratedFilter: "both",
            maxGames: 100,
            maxDays: 30,
        });

        const requestUrl = requests[0].url;
        expect(requestUrl).toContain("perfType=blitz");
        expect(requestUrl).toContain("sort=dateDesc");
        expect(requestUrl).toContain("pgnInJson=true");
        expect(requestUrl).toContain("clocks=true");
        expect(requestUrl).toContain("evals=true");
        expect(requestUrl).toContain("opening=true");
        expect(requestUrl).not.toContain("rated=true");
        expect(getRequestHeaders(requests[0].init).Accept).toBe("application/x-ndjson");

        // Crazyhouse is skipped; the rest are sorted oldest -> newest.
        expect(games.map((game) => game.id)).toEqual([
            "aaaa1111",
            "bbbb2222",
            "cccc3333",
            "dddd4444",
            "eeee5555",
        ]);
        expect(games.map((game) => game.termination)).toEqual([
            "checkmate",
            "resign",
            "draw",
            "timeout",
            "abandon",
        ]);
        expect(games.map((game) => game.result)).toEqual(["win", "loss", "draw", "loss", "draw"]);

        const win = games[0];
        expect(win.source).toBe("lichess");
        expect(win.url).toBe("https://lichess.org/aaaa1111");
        expect(win.end).toBe(Math.floor((nowMs - 3_540_000) / 1000));
        expect(win.start).toBe(Math.floor((nowMs - 3_600_000) / 1000));
        // Post-game rating = rating + ratingDiff.
        expect(win.rating).toBe(1508);
        expect(win.opp).toBe(1520);
        expect(win.oppName).toBe("Nemesis");
        expect(win.color).toBe("w");
        expect(win.timeControl).toEqual({ base: 180, inc: 2 });
        expect(win.eco).toBe("B90");
        expect(win.openingName).toBe("Sicilian Defense: Najdorf Variation");
        expect(win.pgn).toContain("[%eval 0.2]");

        // Casual game without ratingDiff keeps its listed rating.
        expect(games[1].rating).toBe(1495);
        expect(games[1].rated).toBe(false);
        // Black side with ratingDiff +1.
        expect(games[2].color).toBe("b");
        expect(games[2].rating).toBe(1503);
        // Timeout loss applies the negative ratingDiff.
        expect(games[3].rating).toBe(1494);
    });

    it("filters casual client-side and requests rated=true server-side", async () => {
        const nowMs = Date.now();
        stubLichessFetch(nowMs);
        const casual = await fetchStatsGames({
            source: "lichess",
            username: "LichUser",
            timeClass: "blitz",
            ratedFilter: "casual",
            maxGames: 100,
            maxDays: 30,
        });
        expect(casual.map((game) => game.id)).toEqual(["bbbb2222", "eeee5555"]);

        const { requests } = stubLichessFetch(nowMs);
        const rated = await fetchStatsGames({
            source: "lichess",
            username: "LichUser",
            timeClass: "blitz",
            ratedFilter: "rated",
            maxGames: 100,
            maxDays: 30,
        });
        expect(requests[0].url).toContain("rated=true");
        expect(rated.map((game) => game.id)).toEqual(["aaaa1111", "cccc3333", "dddd4444"]);
    });

    it("sends the bearer token when a lichess token is provided", async () => {
        const nowMs = Date.now();
        const { requests } = stubLichessFetch(nowMs);
        await fetchStatsGames({
            source: "lichess",
            username: "LichUser",
            timeClass: "blitz",
            ratedFilter: "both",
            maxGames: 100,
            maxDays: 30,
            lichessToken: "lip_token123",
        });
        expect(getRequestHeaders(requests[0].init).Authorization).toBe("Bearer lip_token123");
    });
});

describe("fetchCurrentRating", () => {
    it("reads chess.com stats for the selected time class", async () => {
        stubFetch((url) => {
            if (url === "https://api.chess.com/pub/player/StatsGuy/stats") {
                return { json: { chess_blitz: { last: { rating: 1587 } } } };
            }
            return null;
        });
        await expect(
            fetchCurrentRating({ source: "chesscom", username: "StatsGuy", timeClass: "blitz" }),
        ).resolves.toBe(1587);
    });

    it("returns null for chess.com classical without fetching", async () => {
        const { mock } = stubFetch(() => null);
        await expect(
            fetchCurrentRating({
                source: "chesscom",
                username: "StatsGuy",
                timeClass: "classical",
            }),
        ).resolves.toBeNull();
        expect(mock).not.toHaveBeenCalled();
    });

    it("returns null when the stats request fails", async () => {
        stubFetch(() => ({ status: 404 }));
        await expect(
            fetchCurrentRating({ source: "chesscom", username: "StatsGuy", timeClass: "blitz" }),
        ).resolves.toBeNull();
    });

    it("reads lichess perfs, mapping daily to correspondence", async () => {
        stubFetch((url) => {
            if (url === "https://lichess.org/api/user/LichUser") {
                return {
                    json: {
                        perfs: {
                            rapid: { rating: 1642 },
                            correspondence: { rating: 1701 },
                        },
                    },
                };
            }
            return null;
        });
        await expect(
            fetchCurrentRating({ source: "lichess", username: "LichUser", timeClass: "rapid" }),
        ).resolves.toBe(1642);
        await expect(
            fetchCurrentRating({ source: "lichess", username: "LichUser", timeClass: "daily" }),
        ).resolves.toBe(1701);
    });
});
