import { describe, expect, test } from "vitest";
import { getOpeningBook, matchBook } from "@/web/statsOpeningBook";
import {
    aggregateProfile,
    anchoredPerformance,
    anchoredStrength,
    buildGameQualityStats,
    clockFeaturesForSide,
    estimateRating,
    gamePerformance,
    replayGamePositions,
    timeClassOf,
    type AnalyzedGameEntry,
    type EvalScore,
    type GamePhaseStats,
    type GameQualityStats,
    type StrengthPhase,
    type StrengthPool,
} from "@/web/statsStrength";

// ALL expected values below are golden fixtures generated by executing the
// ORIGINAL EloGuard lib/review-core.js (plus the verbatim content.js
// clockFeaturesForSide) in node over the exact same inputs
// (scratchpad/gen-strength-fixtures.cjs). Floats are asserted to 1e-9,
// integers exactly.

const cp = (value: number): EvalScore => ({ cp: value });
const mate = (value: number): EvalScore => ({ mate: value });

function close(actual: number | null | undefined, expected: number) {
    expect(actual).not.toBeNull();
    expect(actual).toBeCloseTo(expected, 9);
}

// Rounds to 9 decimals so float goldens compare exactly (the port is an
// operation-for-operation copy, so values are expected to be bit-identical).
function norm(value: number | null | undefined): number | null {
    return typeof value === "number" ? Number(value.toFixed(9)) : null;
}

function expectPhase(
    actual: GamePhaseStats | undefined,
    expected: {
        accuracy: number | null;
        acpl: number | null;
        scoredCount: number;
        complexity: number;
    },
) {
    expect(actual).toBeDefined();
    const phase = actual as GamePhaseStats;
    expect({
        accuracy: norm(phase.accuracy),
        acpl: norm(phase.acpl),
        scoredCount: phase.scoredCount,
        complexity: norm(phase.complexity),
    }).toEqual({
        accuracy: norm(expected.accuracy),
        acpl: norm(expected.acpl),
        scoredCount: expected.scoredCount,
        complexity: norm(expected.complexity),
    });
}

// ---------------------------------------------------------------------------
// timeClassOf
// ---------------------------------------------------------------------------

describe("timeClassOf", () => {
    test("matches review-core pool boundaries", () => {
        expect(timeClassOf({ base: 600, inc: 0 })).toBe("rapid");
        expect(timeClassOf({ base: 180, inc: 0 })).toBe("blitz");
        expect(timeClassOf({ base: 179, inc: 0 })).toBe("bullet");
        expect(timeClassOf({ base: 60, inc: 3 })).toBe("blitz");
        expect(timeClassOf({ base: 0, inc: 0 })).toBe("bullet");
        expect(timeClassOf({ base: 5400, inc: 0 })).toBe("classical");
        expect(timeClassOf({ base: 900, inc: 10 })).toBe("rapid");
        expect(timeClassOf(null)).toBe("rapid");
        expect(timeClassOf("bullet")).toBe("bullet");
        expect(timeClassOf("classical")).toBe("classical");
    });
});

// ---------------------------------------------------------------------------
// estimateRating / gamePerformance / anchoredStrength / anchoredPerformance
// ---------------------------------------------------------------------------

type StatBlobFixture = {
    name: string;
    stats: GameQualityStats & { phases?: Partial<Record<StrengthPhase, GamePhaseStats>> };
    tc: { base: number; inc: number } | string;
    rating: number;
    pool: StrengthPool;
    skillFeature: number;
    perfFeature: number;
    estimateRating: { rating: number; uncertainty: number; pool: StrengthPool };
    estimateRatingOpening: { rating: number; uncertainty: number; pool: StrengthPool };
    estimateRatingEndgame: { rating: number; uncertainty: number; pool: StrengthPool };
    gamePerformance: { perf: number; delta: number; baseline: number; pool: StrengthPool };
    anchoredStrength: {
        strength: number;
        delta: number;
        baseline: number;
        uncertainty: number;
        lambda: number;
        pool: StrengthPool;
    };
    anchoredStrengthOffset: {
        strength: number;
        delta: number;
        baseline: number;
        uncertainty: number;
        lambda: number;
        pool: StrengthPool;
    };
    anchoredPerformance: {
        strength: number;
        delta: number;
        baseline: number;
        uncertainty: number;
        pool: StrengthPool;
    };
};

const statBlobs: StatBlobFixture[] = [
    {
        name: "rapid-typical-d12",
        stats: {
            accuracy: 84.2,
            acpl: 45.3,
            scoredCount: 38,
            complexity: 5.1,
            bookMoves: 6,
            blunderRate: 0.0263,
            fastRate: 0.32,
            scramble: 0.05,
            analysisDepth: 12,
        },
        tc: { base: 600, inc: 0 },
        rating: 1450,
        pool: "rapid",
        skillFeature: 2936.93935894587,
        perfFeature: 2047.1514689458704,
        estimateRating: { rating: 1700, uncertainty: 500, pool: "rapid" },
        estimateRatingOpening: { rating: 1625, uncertainty: 500, pool: "rapid" },
        estimateRatingEndgame: { rating: 1750, uncertainty: 500, pool: "rapid" },
        gamePerformance: { perf: 1550, delta: 100, baseline: 1450, pool: "rapid" },
        anchoredStrength: {
            strength: 1515,
            delta: 65,
            baseline: 1450,
            uncertainty: 175,
            lambda: 0.034,
            pool: "rapid",
        },
        anchoredStrengthOffset: {
            strength: 1515,
            delta: 65,
            baseline: 1450,
            uncertainty: 175,
            lambda: 0.034,
            pool: "rapid",
        },
        anchoredPerformance: {
            strength: 1550,
            delta: 100,
            baseline: 1450,
            uncertainty: 300,
            pool: "rapid",
        },
    },
    {
        name: "bullet-strong-depthnull",
        stats: {
            accuracy: 92.5,
            acpl: 22.1,
            scoredCount: 61,
            complexity: 3.2,
            bookMoves: 14,
            blunderRate: 0,
            fastRate: 0.61,
            scramble: 0,
            analysisDepth: null,
        },
        tc: { base: 60, inc: 0 },
        rating: 2105,
        pool: "bullet",
        skillFeature: 5417.963603864978,
        perfFeature: 2510.0147838649777,
        estimateRating: { rating: 3025, uncertainty: 400, pool: "bullet" },
        estimateRatingOpening: { rating: 2975, uncertainty: 400, pool: "bullet" },
        estimateRatingEndgame: { rating: 3050, uncertainty: 400, pool: "bullet" },
        gamePerformance: { perf: 2250, delta: 150, baseline: 2105, pool: "bullet" },
        anchoredStrength: {
            strength: 2355,
            delta: 250,
            baseline: 2105,
            uncertainty: 150,
            lambda: 0.054,
            pool: "bullet",
        },
        anchoredStrengthOffset: {
            strength: 2350,
            delta: 245,
            baseline: 2105,
            uncertainty: 150,
            lambda: 0.054,
            pool: "bullet",
        },
        anchoredPerformance: {
            strength: 2260,
            delta: 155,
            baseline: 2105,
            uncertainty: 200,
            pool: "bullet",
        },
    },
    {
        name: "blitz-weak-highcx-d18",
        stats: {
            accuracy: 60.4,
            acpl: 145.7,
            scoredCount: 18,
            complexity: 8.9,
            bookMoves: 1,
            blunderRate: 0.2222222222222222,
            fastRate: null,
            scramble: null,
            analysisDepth: 18,
        },
        tc: { base: 180, inc: 2 },
        rating: 820,
        pool: "blitz",
        skillFeature: -603.4693810800361,
        perfFeature: 675.202610031075,
        estimateRating: { rating: 750, uncertainty: 500, pool: "blitz" },
        estimateRatingOpening: { rating: 625, uncertainty: 500, pool: "blitz" },
        estimateRatingEndgame: { rating: 825, uncertainty: 500, pool: "blitz" },
        gamePerformance: { perf: 525, delta: -300, baseline: 820, pool: "blitz" },
        anchoredStrength: {
            strength: 770,
            delta: -50,
            baseline: 820,
            uncertainty: 175,
            lambda: 0.017,
            pool: "blitz",
        },
        anchoredStrengthOffset: {
            strength: 770,
            delta: -50,
            baseline: 820,
            uncertainty: 175,
            lambda: 0.017,
            pool: "blitz",
        },
        anchoredPerformance: {
            strength: 520,
            delta: -300,
            baseline: 820,
            uncertainty: 425,
            pool: "blitz",
        },
    },
    {
        name: "legacy-string-tc-missing-extras",
        stats: {
            accuracy: 77.7,
            acpl: 68.9,
            scoredCount: 25,
            complexity: 4.5,
            bookMoves: null,
            blunderRate: null,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        },
        tc: "rapid",
        rating: 1500,
        pool: "rapid",
        skillFeature: 1228.9443803635977,
        perfFeature: 1228.9443803635977,
        estimateRating: { rating: 1100, uncertainty: 500, pool: "rapid" },
        estimateRatingOpening: { rating: 1025, uncertainty: 500, pool: "rapid" },
        estimateRatingEndgame: { rating: 1125, uncertainty: 500, pool: "rapid" },
        gamePerformance: { perf: 1200, delta: -300, baseline: 1500, pool: "rapid" },
        anchoredStrength: {
            strength: 1480,
            delta: -20,
            baseline: 1500,
            uncertainty: 175,
            lambda: 0.023,
            pool: "rapid",
        },
        anchoredStrengthOffset: {
            strength: 1480,
            delta: -20,
            baseline: 1500,
            uncertainty: 175,
            lambda: 0.023,
            pool: "rapid",
        },
        anchoredPerformance: {
            strength: 1190,
            delta: -310,
            baseline: 1500,
            uncertainty: 375,
            pool: "rapid",
        },
    },
    {
        name: "rapid-increment-d12",
        stats: {
            accuracy: 88.1,
            acpl: 33.3,
            scoredCount: 44,
            complexity: 6.7,
            bookMoves: 9,
            blunderRate: 0.0455,
            fastRate: 0.5,
            scramble: 0.12,
            analysisDepth: 12,
        },
        tc: { base: 900, inc: 10 },
        rating: 1985,
        pool: "rapid",
        skillFeature: 4012.417751972741,
        perfFeature: 2401.8339819727407,
        estimateRating: { rating: 2350, uncertainty: 500, pool: "rapid" },
        estimateRatingOpening: { rating: 2275, uncertainty: 500, pool: "rapid" },
        estimateRatingEndgame: { rating: 2400, uncertainty: 500, pool: "rapid" },
        gamePerformance: { perf: 2075, delta: 100, baseline: 1985, pool: "rapid" },
        anchoredStrength: {
            strength: 2110,
            delta: 125,
            baseline: 1985,
            uncertainty: 175,
            lambda: 0.039,
            pool: "rapid",
        },
        anchoredStrengthOffset: {
            strength: 2110,
            delta: 125,
            baseline: 1985,
            uncertainty: 175,
            lambda: 0.039,
            pool: "rapid",
        },
        anchoredPerformance: {
            strength: 2095,
            delta: 110,
            baseline: 1985,
            uncertainty: 275,
            pool: "rapid",
        },
    },
    {
        name: "classical-elite",
        stats: {
            accuracy: 95.0,
            acpl: 15.2,
            scoredCount: 72,
            complexity: 4.0,
            bookMoves: 16,
            blunderRate: 0.01,
            fastRate: 0.2,
            scramble: 0.0,
            analysisDepth: null,
        },
        tc: { base: 5400, inc: 30 },
        rating: 2300,
        pool: "classical",
        skillFeature: 5695.104375197184,
        perfFeature: 2543.2125551971844,
        estimateRating: { rating: 3200, uncertainty: 475, pool: "classical" },
        estimateRatingOpening: { rating: 3200, uncertainty: 475, pool: "classical" },
        estimateRatingEndgame: { rating: 3200, uncertainty: 475, pool: "classical" },
        gamePerformance: { perf: 2425, delta: 125, baseline: 2300, pool: "classical" },
        anchoredStrength: {
            strength: 2655,
            delta: 355,
            baseline: 2300,
            uncertainty: 175,
            lambda: 0.063,
            pool: "classical",
        },
        anchoredStrengthOffset: {
            strength: 2655,
            delta: 355,
            baseline: 2300,
            uncertainty: 175,
            lambda: 0.063,
            pool: "classical",
        },
        anchoredPerformance: {
            strength: 2415,
            delta: 115,
            baseline: 2300,
            uncertainty: 225,
            pool: "classical",
        },
    },
    {
        name: "blitz-with-phases",
        stats: {
            accuracy: 82.4,
            acpl: 51.6,
            scoredCount: 31,
            complexity: 4.9,
            bookMoves: 7,
            blunderRate: 0.0645,
            fastRate: 0.42,
            scramble: 0.1,
            analysisDepth: 12,
            phases: {
                opening: { accuracy: 91.2, acpl: 21.4, scoredCount: 8, complexity: 3.1 },
                middlegame: { accuracy: 79.9, acpl: 62.0, scoredCount: 17, complexity: 5.7 },
                endgame: { accuracy: 81.0, acpl: 55.0, scoredCount: 6, complexity: 4.8 },
            },
        },
        tc: { base: 180, inc: 0 },
        rating: 1610,
        pool: "blitz",
        skillFeature: 3114.2579013565964,
        perfFeature: 1990.8962313565971,
        estimateRating: { rating: 1725, uncertainty: 275, pool: "blitz" },
        estimateRatingOpening: { rating: 1675, uncertainty: 275, pool: "blitz" },
        estimateRatingEndgame: { rating: 1750, uncertainty: 300, pool: "blitz" },
        gamePerformance: { perf: 1625, delta: 25, baseline: 1610, pool: "blitz" },
        anchoredStrength: {
            strength: 1645,
            delta: 35,
            baseline: 1610,
            uncertainty: 100,
            lambda: 0.028,
            pool: "blitz",
        },
        anchoredStrengthOffset: {
            strength: 1645,
            delta: 35,
            baseline: 1610,
            uncertainty: 100,
            lambda: 0.028,
            pool: "blitz",
        },
        anchoredPerformance: {
            strength: 1645,
            delta: 35,
            baseline: 1610,
            uncertainty: 175,
            pool: "blitz",
        },
    },
];

describe("estimateRating / gamePerformance / anchored estimators", () => {
    for (const blob of statBlobs) {
        test(`golden fixture: ${blob.name}`, () => {
            expect(estimateRating(blob.stats, blob.tc)).toEqual(blob.estimateRating);
            expect(estimateRating(blob.stats, blob.tc, "opening")).toEqual(
                blob.estimateRatingOpening,
            );
            expect(estimateRating(blob.stats, blob.tc, "endgame")).toEqual(
                blob.estimateRatingEndgame,
            );
            expect(gamePerformance(blob.stats, blob.tc, blob.rating)).toEqual(blob.gamePerformance);
            expect(gamePerformance(blob.stats, blob.tc, null)).toBeNull();
            expect(
                anchoredStrength(blob.skillFeature, blob.stats.scoredCount, blob.pool, blob.rating),
            ).toEqual(blob.anchoredStrength);
            expect(
                anchoredStrength(
                    blob.skillFeature,
                    blob.stats.scoredCount,
                    blob.pool,
                    blob.rating,
                    -54,
                ),
            ).toEqual(blob.anchoredStrengthOffset);
            expect(
                anchoredPerformance(
                    blob.perfFeature,
                    blob.stats.scoredCount,
                    blob.pool,
                    blob.rating,
                ),
            ).toEqual(blob.anchoredPerformance);
            expect(
                anchoredPerformance(null, blob.stats.scoredCount, blob.pool, blob.rating),
            ).toBeNull();
            expect(
                anchoredPerformance(blob.perfFeature, blob.stats.scoredCount, blob.pool, null),
            ).toBeNull();
        });
    }

    test("estimateRating returns null without scored accuracy", () => {
        const empty: GameQualityStats = {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
            bookMoves: 0,
            blunderRate: 0,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        };
        expect(estimateRating(empty, { base: 600, inc: 0 })).toBeNull();
        expect(gamePerformance(empty, { base: 600, inc: 0 }, 1500)).toBeNull();
    });

    test("anchored estimator edge fixtures", () => {
        expect(anchoredStrength(1650.5, 120, "blitz", 1500)).toEqual({
            strength: 1505,
            delta: 5,
            baseline: 1500,
            uncertainty: 150,
            lambda: 0.101,
            pool: "blitz",
        });
        expect(anchoredStrength(1200, 4, "bullet", 900, -54)).toEqual({
            strength: 900,
            delta: 0,
            baseline: 900,
            uncertainty: 175,
            lambda: 0.004,
            pool: "bullet",
        });
        expect(anchoredStrength(2960.25, 30, "rapid", 2900)).toEqual({
            strength: 2925,
            delta: 25,
            baseline: 2900,
            uncertainty: 175,
            lambda: 0.027,
            pool: "rapid",
        });
        expect(anchoredStrength(1500, 12, "classical", 1600)).toEqual({
            strength: 1595,
            delta: -5,
            baseline: 1600,
            uncertainty: 175,
            lambda: 0.011,
            pool: "classical",
        });
        expect(anchoredStrength(700, 300, "rapid", 350)).toEqual({
            strength: 210,
            delta: -140,
            baseline: 350,
            uncertainty: 150,
            lambda: 0.219,
            pool: "rapid",
        });
        expect(anchoredPerformance(1700, 35, "blitz", 1450)).toEqual({
            strength: 1460,
            delta: 10,
            baseline: 1450,
            uncertainty: 250,
            pool: "blitz",
        });
        expect(anchoredPerformance(900.75, 10, "bullet", 700)).toEqual({
            strength: 670,
            delta: -30,
            baseline: 700,
            uncertainty: 500,
            pool: "bullet",
        });
        expect(anchoredPerformance(2600, 80, "rapid", 2450)).toEqual({
            strength: 2515,
            delta: 65,
            baseline: 2450,
            uncertainty: 200,
            pool: "rapid",
        });
        expect(anchoredPerformance(2100, 1, "classical", 2985)).toEqual({
            strength: 2650,
            delta: -335,
            baseline: 2985,
            uncertainty: 500,
            pool: "classical",
        });
    });
});

// ---------------------------------------------------------------------------
// aggregateProfile
// ---------------------------------------------------------------------------

const NOW_MS = 1753500000000;
const DAY_MS = 86400000;

function makeEntry(
    index: number,
    ts: number,
    timeControl: { base: number; inc: number } | null,
    stats: GameQualityStats,
    phases: Partial<Record<StrengthPhase, GamePhaseStats>>,
): AnalyzedGameEntry {
    return {
        v: 2,
        ts,
        key: `test|${index}`,
        end: Math.floor(ts / 1000),
        source: "test",
        url: null,
        timeControl,
        color: "w",
        opponent: null,
        opp: null,
        result: "win",
        plies: 60,
        eco: null,
        openingName: null,
        stats,
        phases,
        counts: { inaccuracy: 0, mistake: 0, blunder: 0 },
        phaseBlunders: { opening: 0, middlegame: 0, endgame: 0 },
    };
}

const aggregateEntries: AnalyzedGameEntry[] = [
    makeEntry(
        0,
        NOW_MS - 2 * DAY_MS,
        { base: 600, inc: 0 },
        {
            accuracy: 85.5,
            acpl: 42.0,
            scoredCount: 40,
            complexity: 5.0,
            bookMoves: 8,
            blunderRate: 0.05,
            fastRate: 0.4,
            scramble: 0.08,
            analysisDepth: 12,
        },
        {
            opening: { accuracy: 88.0, acpl: 30.0, scoredCount: 10, complexity: 3.5 },
            middlegame: { accuracy: 84.0, acpl: 50.0, scoredCount: 20, complexity: 5.8 },
            endgame: { accuracy: 83.0, acpl: 45.0, scoredCount: 10, complexity: 4.9 },
        },
    ),
    makeEntry(
        1,
        NOW_MS - 60 * DAY_MS,
        { base: 900, inc: 10 },
        {
            accuracy: 78.3,
            acpl: 61.2,
            scoredCount: 33,
            complexity: 4.2,
            bookMoves: 4,
            blunderRate: 0.09,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        },
        {
            opening: { accuracy: 80.0, acpl: 40.0, scoredCount: 4, complexity: 3.0 },
            middlegame: { accuracy: 77.0, acpl: 70.0, scoredCount: 21, complexity: 4.6 },
            endgame: { accuracy: 79.0, acpl: 55.0, scoredCount: 8, complexity: 4.0 },
        },
    ),
    makeEntry(
        2,
        NOW_MS - 10 * DAY_MS,
        { base: 180, inc: 0 },
        {
            accuracy: 90.1,
            acpl: 28.4,
            scoredCount: 52,
            complexity: 6.1,
            bookMoves: 12,
            blunderRate: 0.019230769230769232,
            fastRate: 0.55,
            scramble: 0.02,
            analysisDepth: 12,
        },
        {
            opening: { accuracy: 93.0, acpl: 18.0, scoredCount: 14, complexity: 4.0 },
            middlegame: { accuracy: 89.0, acpl: 33.0, scoredCount: 28, complexity: 7.2 },
            endgame: { accuracy: 88.0, acpl: 30.0, scoredCount: 10, complexity: 6.0 },
        },
    ),
    makeEntry(
        3,
        NOW_MS - 100 * DAY_MS,
        { base: 300, inc: 3 },
        {
            accuracy: 72.0,
            acpl: 88.8,
            scoredCount: 27,
            complexity: 3.9,
            bookMoves: 2,
            blunderRate: 0.14814814814814814,
            fastRate: 0.7,
            scramble: 0.15,
            analysisDepth: 10,
        },
        {
            opening: { accuracy: 75.0, acpl: 60.0, scoredCount: 6, complexity: 3.3 },
            middlegame: { accuracy: 70.0, acpl: 100.0, scoredCount: 15, complexity: 4.1 },
            endgame: { accuracy: 74.0, acpl: 90.0, scoredCount: 6, complexity: 4.4 },
        },
    ),
    // filtered out: scoredCount < 6
    makeEntry(
        4,
        NOW_MS - 1 * DAY_MS,
        { base: 600, inc: 0 },
        {
            accuracy: 95.0,
            acpl: 10.0,
            scoredCount: 5,
            complexity: 4.5,
            bookMoves: 3,
            blunderRate: 0,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        },
        {},
    ),
    // filtered out: no timeControl
    makeEntry(
        5,
        NOW_MS - 3 * DAY_MS,
        null,
        {
            accuracy: 82.0,
            acpl: 40.0,
            scoredCount: 30,
            complexity: 4.5,
            bookMoves: 5,
            blunderRate: 0.03,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        },
        {},
    ),
    // filtered out: accuracy null
    makeEntry(
        6,
        NOW_MS - 4 * DAY_MS,
        { base: 180, inc: 0 },
        {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
            bookMoves: 0,
            blunderRate: 0,
            fastRate: null,
            scramble: null,
            analysisDepth: null,
        },
        {},
    ),
];

type PoolGolden = {
    estimate: { rating: number; uncertainty: number; pool: StrengthPool };
    games: number;
    accuracy: number;
    aggFeature: number;
    effMoves: number;
};
type PhaseGolden = {
    estimate: { rating: number; uncertainty: number };
    moves: number;
    accuracy: number;
    aggFeature: number;
    effMoves: number;
};

function expectProfile(
    actual: ReturnType<typeof aggregateProfile>,
    expected: {
        primaryPool: StrengthPool;
        pools: Partial<Record<StrengthPool, PoolGolden>>;
        phases: Record<StrengthPhase, PhaseGolden>;
        recent: { key: string; rating: number; pool: StrengthPool }[];
    },
) {
    expect(actual.totalGames).toBe(4);
    expect(actual.primaryPool).toBe(expected.primaryPool);
    expect(Object.keys(actual.pools).sort()).toEqual(Object.keys(expected.pools).sort());
    for (const [pool, golden] of Object.entries(expected.pools) as [StrengthPool, PoolGolden][]) {
        const profile = actual.pools[pool];
        expect(profile).toBeDefined();
        expect(profile?.pool).toBe(pool);
        expect(profile?.games).toBe(golden.games);
        expect(profile?.estimate).toEqual(golden.estimate);
        close(profile?.accuracy, golden.accuracy);
        close(profile?.aggFeature, golden.aggFeature);
        close(profile?.effMoves, golden.effMoves);
    }
    for (const [phase, golden] of Object.entries(expected.phases) as [
        StrengthPhase,
        PhaseGolden,
    ][]) {
        const profile = actual.phases[phase];
        expect(profile).toBeDefined();
        expect(profile?.phase).toBe(phase);
        expect(profile?.moves).toBe(golden.moves);
        expect(profile?.estimate).toEqual(golden.estimate);
        close(profile?.accuracy, golden.accuracy);
        close(profile?.aggFeature, golden.aggFeature);
        close(profile?.effMoves, golden.effMoves);
    }
    expect(actual.recent.map((r) => r.entry.key)).toEqual(expected.recent.map((r) => r.key));
    expect(actual.recent.map((r) => r.estimate?.rating)).toEqual(
        expected.recent.map((r) => r.rating),
    );
    expect(actual.recent.map((r) => r.estimate?.pool)).toEqual(expected.recent.map((r) => r.pool));
}

describe("aggregateProfile", () => {
    test("recency-decayed profile matches review-core", () => {
        expectProfile(aggregateProfile(aggregateEntries, NOW_MS), {
            primaryPool: "rapid",
            pools: {
                blitz: {
                    estimate: { rating: 2250, uncertainty: 400, pool: "blitz" },
                    games: 2,
                    accuracy: 88.0204255319149,
                    aggFeature: 2542.4250654291263,
                    effMoves: 50.36308399261803,
                },
                rapid: {
                    estimate: { rating: 1725, uncertainty: 500, pool: "rapid" },
                    games: 2,
                    accuracy: 83.68259588530645,
                    aggFeature: 1964.034553561166,
                    effMoves: 51.88258446460637,
                },
            },
            phases: {
                opening: {
                    estimate: { rating: 1325, uncertainty: 500 },
                    moves: 34,
                    accuracy: 89.24501328779863,
                    aggFeature: 2324.294528570501,
                    effMoves: 24.571314232658008,
                },
                middlegame: {
                    estimate: { rating: 1550, uncertainty: 500 },
                    moves: 84,
                    accuracy: 84.30343027936127,
                    aggFeature: 2336.773367689034,
                    effMoves: 54.94461487135247,
                },
                endgame: {
                    estimate: { rating: 1400, uncertainty: 500 },
                    moves: 34,
                    accuracy: 83.81787990040296,
                    aggFeature: 2233.150683865677,
                    effMoves: 22.729739353213915,
                },
            },
            recent: [
                { key: "test|0", rating: 1875, pool: "rapid" },
                { key: "test|2", rating: 2400, pool: "blitz" },
                { key: "test|1", rating: 1000, pool: "rapid" },
                { key: "test|3", rating: 850, pool: "blitz" },
            ],
        });
    });

    test("noDecay profile matches review-core", () => {
        expectProfile(aggregateProfile(aggregateEntries, NOW_MS, { noDecay: true }), {
            primaryPool: "blitz",
            pools: {
                blitz: {
                    estimate: { rating: 2075, uncertainty: 400, pool: "blitz" },
                    games: 2,
                    accuracy: 83.91392405063291,
                    aggFeature: 2176.905909378567,
                    effMoves: 79,
                },
                rapid: {
                    estimate: { rating: 1575, uncertainty: 475, pool: "rapid" },
                    games: 2,
                    accuracy: 82.24520547945205,
                    aggFeature: 1766.471326985073,
                    effMoves: 73,
                },
            },
            phases: {
                opening: {
                    estimate: { rating: 1500, uncertainty: 425 },
                    moves: 34,
                    accuracy: 86.82352941176471,
                    aggFeature: 2103.0291154698684,
                    effMoves: 34,
                },
                middlegame: {
                    estimate: { rating: 1600, uncertainty: 275 },
                    moves: 84,
                    accuracy: 81.41666666666667,
                    aggFeature: 2036.6751449673034,
                    effMoves: 84,
                },
                endgame: {
                    estimate: { rating: 1575, uncertainty: 350 },
                    moves: 34,
                    accuracy: 81.94117647058823,
                    aggFeature: 2069.988620626912,
                    effMoves: 34,
                },
            },
            recent: [
                { key: "test|0", rating: 1875, pool: "rapid" },
                { key: "test|2", rating: 2400, pool: "blitz" },
                { key: "test|1", rating: 1000, pool: "rapid" },
                { key: "test|3", rating: 850, pool: "blitz" },
            ],
        });
    });

    test("empty input yields an empty profile", () => {
        expect(aggregateProfile([], NOW_MS)).toEqual({
            pools: {},
            phases: {},
            recent: [],
            primaryPool: null,
            totalGames: 0,
        });
        // Entries that all fail the accuracy/scoredCount/timeControl filter.
        expect(aggregateProfile(aggregateEntries.slice(4), NOW_MS).totalGames).toBe(0);
    });
});

// ---------------------------------------------------------------------------
// opening book
// ---------------------------------------------------------------------------

describe("statsOpeningBook", () => {
    test("lazy book is a shared singleton", async () => {
        const first = await getOpeningBook();
        const second = await getOpeningBook();
        expect(second).toBe(first);
        expect(first.length).toBe(3733);
    });

    test("matchBook matches review-core prefix semantics", async () => {
        const book = await getOpeningBook();
        expect(matchBook(["e4", "e5", "Nf3", "Nc6", "Bb5", "a6"], book)).toEqual({
            plies: 6,
            eco: "C70",
            name: "Ruy Lopez: Morphy Defense",
        });
        // Prefix continues past the deepest complete line ("e4 g5" = Borg Defense,
        // "e4 g5 d4" is only a prefix of longer lines, "f6" leaves book).
        expect(matchBook(["e4", "g5", "d4", "f6"], book)).toEqual({
            plies: 3,
            eco: "B00",
            name: "Borg Defense",
        });
        expect(matchBook(["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"], book)).toEqual({
            plies: 8,
            eco: "E70",
            name: "King's Indian Defense: Normal Variation",
        });
        expect(matchBook(["h4", "h5", "a4"], book)).toEqual({
            plies: 1,
            eco: "A00",
            name: "Kádas Opening",
        });
        expect(matchBook([], book)).toEqual({ plies: 0, eco: null, name: null });
    });
});

// ---------------------------------------------------------------------------
// replayGamePositions + clockFeaturesForSide
// ---------------------------------------------------------------------------

// Game 1: Damiano punishment, 16 plies with two forced king moves.
const game1Sans = [
    "e4",
    "e5",
    "Nf3",
    "f6",
    "Nxe5",
    "fxe5",
    "Qh5+",
    "Ke7",
    "Qxe5+",
    "Kf7",
    "Bc4+",
    "Kg6",
    "Qf5+",
    "Kh6",
    "d4+",
    "g5",
];
const game1LegalCounts = [20, 20, 29, 29, 27, 25, 27, 2, 38, 1, 42, 2, 49, 1, 50, 2, 54];
const game1UciMoves = [
    "e2e4",
    "e7e5",
    "g1f3",
    "f7f6",
    "f3e5",
    "f6e5",
    "d1h5",
    "e8e7",
    "h5e5",
    "e7f7",
    "f1c4",
    "f7g6",
    "e5f5",
    "g6h6",
    "d2d4",
    "g7g5",
];

// Game 2: the Opera Game, 33 plies with queenside castling and mate.
const game2Sans = [
    "e4",
    "e5",
    "Nf3",
    "d6",
    "d4",
    "Bg4",
    "dxe5",
    "Bxf3",
    "Qxf3",
    "dxe5",
    "Bc4",
    "Nf6",
    "Qb3",
    "Qe7",
    "Nc3",
    "c6",
    "Bg5",
    "b5",
    "Nxb5",
    "cxb5",
    "Bxb5+",
    "Nbd7",
    "O-O-O",
    "Rd8",
    "Rxd7",
    "Rxd7",
    "Rd1",
    "Qe6",
    "Bxd7+",
    "Nxd7",
    "Qb8+",
    "Nxb8",
    "Rd8#",
];
const game2LegalCounts = [
    20, 20, 29, 29, 27, 33, 35, 36, 35, 29, 40, 37, 45, 36, 44, 29, 41, 27, 43, 27, 44, 5, 49, 22,
    51, 22, 42, 18, 47, 4, 46, 1, 33, 0,
];
const game2UciMoves = [
    "e2e4",
    "e7e5",
    "g1f3",
    "d7d6",
    "d2d4",
    "c8g4",
    "d4e5",
    "g4f3",
    "d1f3",
    "d6e5",
    "f1c4",
    "g8f6",
    "f3b3",
    "d8e7",
    "b1c3",
    "c7c6",
    "c1g5",
    "b7b5",
    "c3b5",
    "c6b5",
    "c4b5",
    "b8d7",
    "e1c1",
    "a8d8",
    "d1d7",
    "d8d7",
    "h1d1",
    "e7e6",
    "b5d7",
    "f6d7",
    "b3b8",
    "d7b8",
    "d1d8",
];

describe("replayGamePositions", () => {
    test("legal counts and UCI moves match chess.js exactly (game 1)", () => {
        const replay = replayGamePositions(game1Sans);
        expect(replay).not.toBeNull();
        expect(replay?.fens).toHaveLength(17);
        expect(replay?.fens[0]).toBe("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");
        expect(replay?.legalCounts).toEqual(game1LegalCounts);
        expect(replay?.uciMoves).toEqual(game1UciMoves);
    });

    test("legal counts and UCI moves match chess.js exactly (game 2, castling + mate)", () => {
        const replay = replayGamePositions(game2Sans);
        expect(replay).not.toBeNull();
        expect(replay?.fens).toHaveLength(34);
        expect(replay?.legalCounts).toEqual(game2LegalCounts);
        expect(replay?.uciMoves).toEqual(game2UciMoves);
    });

    test("returns null on illegal or unparseable SANs", () => {
        expect(replayGamePositions(["e4", "e4"])).toBeNull();
        expect(replayGamePositions(["nonsense"])).toBeNull();
    });
});

describe("clockFeaturesForSide", () => {
    const clocks = [
        300,
        292,
        279,
        271,
        282,
        274,
        261,
        253,
        264,
        256,
        243,
        null,
        246,
        238,
        225,
        217,
        228,
        220,
        207,
        199,
        210,
        202,
        189,
        181,
        192,
        184,
        171,
        163,
        174,
        166,
    ];
    const sans = new Array<string>(30).fill("x");
    const tc = { base: 300, inc: 0 };

    test("fast/scramble rates match content.js", () => {
        expect(clockFeaturesForSide(sans, clocks, tc, 4, "w")).toEqual({
            fastRate: 0.5384615384615384,
            scramble: 0,
        });
        expect(clockFeaturesForSide(sans, clocks, tc, 4, "b")).toEqual({
            fastRate: 0.5454545454545454,
            scramble: 0,
        });
    });

    test("needs at least 8 considered moves", () => {
        expect(clockFeaturesForSide(sans.slice(0, 12), clocks.slice(0, 12), tc, 4, "w")).toEqual({
            fastRate: null,
            scramble: null,
        });
    });
});

// ---------------------------------------------------------------------------
// buildGameQualityStats
// ---------------------------------------------------------------------------

describe("buildGameQualityStats", () => {
    // evals[i] = position after i plies. Designed drops:
    //   i=7 Ke7 (black): ~32% => blunder; i=8 Qxe5+ (white): ~18% => mistake and
    //   bestMoves[8] matches the played move with rawDrop > 6 (must NOT rescue);
    //   i=10 Bc4+ (white): ~6.5% => inaccuracy; i=12 Qf5+ (white): rawDrop ~0.6
    //   with matching best => playedIsBest forces drop/cpLoss to 0.
    const game1Evals: (EvalScore | null)[] = [
        cp(20),
        null,
        cp(25),
        cp(35),
        cp(140),
        cp(150),
        cp(600),
        cp(100),
        cp(650),
        cp(280),
        cp(300),
        cp(215),
        cp(240),
        cp(230),
        mate(5),
        mate(4),
        mate(3),
    ];
    const game1Best: (string | null)[] = [
        null,
        null,
        null,
        null,
        "f3e5",
        null,
        null,
        null,
        "h5e5",
        null,
        "f1b5",
        null,
        "e5f5",
        null,
        null,
        null,
    ];
    const game1Clocks: (number | null)[] = [
        179.5, 179.0, 175.3, 172.0, 170.1, 171.9, 168.0, 165.0, 167.5, 150.2, 140.0, 20.0, 138.5,
        18.4, 137.9, 17.0,
    ];
    const game1Tc = { base: 180, inc: 2 };

    test("game 1 white side matches review-core buildReview", async () => {
        const result = await buildGameQualityStats({
            sans: game1Sans,
            evals: game1Evals,
            bestMoves: game1Best,
            color: "w",
            timeControl: game1Tc,
            clocks: game1Clocks,
            analysisDepth: 12,
        });
        expect(result).not.toBeNull();
        expect(result?.plies).toBe(16);
        close(result?.stats.accuracy, 64.57052336812725);
        close(result?.stats.acpl, 113.75);
        expect(result?.stats.scoredCount).toBe(4);
        close(result?.stats.complexity, 3.276915466128493);
        expect(result?.stats.bookMoves).toBe(4);
        expect(result?.stats.blunderRate).toBe(0);
        expect(result?.stats.fastRate).toBeNull();
        expect(result?.stats.scramble).toBeNull();
        expect(result?.stats.analysisDepth).toBe(12);
        expectPhase(result?.phases.opening, {
            accuracy: 64.57052336812725,
            acpl: 113.75,
            scoredCount: 4,
            complexity: 3.276915466128493,
        });
        expectPhase(result?.phases.middlegame, {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
        });
        expectPhase(result?.phases.endgame, {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
        });
        expect(result?.counts).toEqual({ inaccuracy: 1, mistake: 1, blunder: 0 });
        expect(result?.phaseBlunders).toEqual({ opening: 0, middlegame: 0, endgame: 0 });
        // End-to-end: the review-core estimate over these stats (with phases).
        expect(
            estimateRating(
                { ...(result?.stats as GameQualityStats), phases: result?.phases },
                game1Tc,
            ),
        ).toEqual({ rating: 1375, uncertainty: 475, pool: "blitz" });
    });

    test("game 1 black side matches review-core buildReview", async () => {
        const result = await buildGameQualityStats({
            sans: game1Sans,
            evals: game1Evals,
            bestMoves: game1Best,
            color: "b",
            timeControl: game1Tc,
            clocks: game1Clocks,
            analysisDepth: 12,
        });
        expect(result).not.toBeNull();
        close(result?.stats.accuracy, 38.6184857398743);
        close(result?.stats.acpl, 191.66666666666666);
        expect(result?.stats.scoredCount).toBe(3);
        close(result?.stats.complexity, 4.490054873732336);
        expect(result?.stats.bookMoves).toBe(3);
        close(result?.stats.blunderRate, 0.3333333333333333);
        expect(result?.stats.fastRate).toBeNull();
        expect(result?.stats.scramble).toBeNull();
        expectPhase(result?.phases.opening, {
            accuracy: 38.6184857398743,
            acpl: 191.66666666666666,
            scoredCount: 3,
            complexity: 4.490054873732336,
        });
        expectPhase(result?.phases.middlegame, {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
        });
        expectPhase(result?.phases.endgame, {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
        });
        expect(result?.counts).toEqual({ inaccuracy: 0, mistake: 0, blunder: 1 });
        expect(result?.phaseBlunders).toEqual({ opening: 1, middlegame: 0, endgame: 0 });
        expect(
            estimateRating(
                { ...(result?.stats as GameQualityStats), phases: result?.phases },
                game1Tc,
            ),
        ).toEqual({ rating: 1325, uncertainty: 500, pool: "blitz" });
    });

    const game2Evals: (EvalScore | null)[] = [
        cp(0),
        null,
        cp(39),
        null,
        cp(-22),
        cp(-54),
        cp(-46),
        cp(1),
        cp(56),
        cp(73),
        cp(33),
        cp(-39),
        cp(-88),
        cp(-72),
        cp(3),
        cp(84),
        cp(106),
        cp(46),
        cp(-57),
        cp(-123),
        cp(-98),
        cp(7),
        cp(450),
        cp(139),
        cp(57),
        cp(-76),
        cp(-380),
        cp(-122),
        cp(11),
        cp(144),
        cp(172),
        mate(2),
        mate(1),
        null, // final position missing => synthesized checkmate eval
    ];
    const game2Best: (string | null)[] = [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "d1f3",
        null,
        null,
        null,
        "a2a3",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "c4b5",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
    ];
    const game2Clocks: (number | null)[] = [
        600,
        555,
        503,
        null,
        526,
        481,
        549,
        504,
        452,
        527,
        null,
        430,
        498,
        453,
        401,
        476,
        424,
        null,
        447,
        402,
        350,
        425,
        373,
        328,
        null,
        351,
        299,
        374,
        322,
        277,
        345,
        null,
        248,
    ];
    const game2Tc = { base: 600, inc: 0 };

    test("game 2 white side matches review-core buildReview", async () => {
        const result = await buildGameQualityStats({
            sans: game2Sans,
            evals: game2Evals,
            bestMoves: game2Best,
            color: "w",
            timeControl: game2Tc,
            clocks: game2Clocks,
            analysisDepth: null,
        });
        expect(result).not.toBeNull();
        expect(result?.plies).toBe(33);
        close(result?.stats.accuracy, 82.70129683421754);
        close(result?.stats.acpl, 49.38461538461539);
        expect(result?.stats.scoredCount).toBe(13);
        close(result?.stats.complexity, 8.215540602389192);
        expect(result?.stats.bookMoves).toBe(4);
        close(result?.stats.blunderRate, 0.07692307692307693);
        close(result?.stats.fastRate, 0.5555555555555556);
        expect(result?.stats.scramble).toBe(0);
        expect(result?.stats.analysisDepth).toBeNull();
        expectPhase(result?.phases.opening, {
            accuracy: 87.81992637230397,
            acpl: 33,
            scoredCount: 6,
            complexity: 5.057135170580486,
        });
        expectPhase(result?.phases.middlegame, {
            accuracy: 76.48313385799327,
            acpl: 74,
            scoredCount: 6,
            complexity: 10.743202801262763,
        });
        expectPhase(result?.phases.endgame, {
            accuracy: 100,
            acpl: 0,
            scoredCount: 1,
            complexity: 12,
        });
        expect(result?.counts).toEqual({ inaccuracy: 3, mistake: 1, blunder: 1 });
        expect(result?.phaseBlunders).toEqual({ opening: 0, middlegame: 1, endgame: 0 });
        expect(
            estimateRating(
                { ...(result?.stats as GameQualityStats), phases: result?.phases },
                game2Tc,
            ),
        ).toEqual({ rating: 1325, uncertainty: 500, pool: "rapid" });
    });

    test("game 2 black side matches review-core buildReview", async () => {
        const result = await buildGameQualityStats({
            sans: game2Sans,
            evals: game2Evals,
            bestMoves: game2Best,
            color: "b",
            timeControl: game2Tc,
            clocks: game2Clocks,
            analysisDepth: null,
        });
        expect(result).not.toBeNull();
        close(result?.stats.accuracy, 75.44421518883381);
        close(result?.stats.acpl, 65.08333333333333);
        expect(result?.stats.scoredCount).toBe(12);
        close(result?.stats.complexity, 7.615253725047078);
        expect(result?.stats.bookMoves).toBe(3);
        close(result?.stats.blunderRate, 0.08333333333333333);
        close(result?.stats.fastRate, 0.7);
        expect(result?.stats.scramble).toBe(0);
        expectPhase(result?.phases.opening, {
            accuracy: 91.26563468636955,
            acpl: 25.285714285714285,
            scoredCount: 7,
            complexity: 4.76968126220983,
        });
        expectPhase(result?.phases.middlegame, {
            accuracy: 63.782859770204766,
            acpl: 120.8,
            scoredCount: 5,
            complexity: 11.599055173019224,
        });
        expectPhase(result?.phases.endgame, {
            accuracy: null,
            acpl: null,
            scoredCount: 0,
            complexity: 4.5,
        });
        expect(result?.counts).toEqual({ inaccuracy: 2, mistake: 1, blunder: 1 });
        expect(result?.phaseBlunders).toEqual({ opening: 0, middlegame: 1, endgame: 0 });
        expect(
            estimateRating(
                { ...(result?.stats as GameQualityStats), phases: result?.phases },
                game2Tc,
            ),
        ).toEqual({ rating: 1275, uncertainty: 500, pool: "rapid" });
    });

    test("returns null on empty or illegal games", async () => {
        expect(
            await buildGameQualityStats({
                sans: [],
                evals: [cp(0)],
                color: "w",
                timeControl: null,
                clocks: [],
                analysisDepth: null,
            }),
        ).toBeNull();
        expect(
            await buildGameQualityStats({
                sans: ["e4", "e4"],
                evals: [cp(0), cp(10), cp(20)],
                color: "w",
                timeControl: null,
                clocks: [null, null],
                analysisDepth: null,
            }),
        ).toBeNull();
    });
});
