
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async closeSplashscreen() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBestMoves(id: string, engine: string, tab: string, goMode: GoMode, options: EngineOptions) : Promise<Result<[number, BestMoves[]] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_best_moves", { id, engine, tab, goMode, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lookupLocalLichessCloudEval(fen: string, multipv: number | null) : Promise<Result<LocalLichessCloudEval | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_local_lichess_cloud_eval", { fen, multipv }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalLichessEvalDbStatus() : Promise<Result<LocalEvalDbStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_lichess_eval_db_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildLocalLichessEvalDb(request: LocalEvalBuildRequest) : Promise<Result<LocalEvalBuildReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_local_lichess_eval_db", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeGame(id: string, engine: string, goMode: GoMode, options: AnalysisOptions, uciOptions: EngineOption[]) : Promise<Result<MoveAnalysis[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_game", { id, engine, goMode, options, uciOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanMistakeReview(request: MistakeReviewScanRequest) : Promise<Result<MistakeReviewScanReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_mistake_review", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMistakeReviewGameMetadata(file: string, gameIds: number[]) : Promise<Result<MistakeReviewGameMetadata[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mistake_review_game_metadata", { file, gameIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMistakeReviewClockTimings(file: string, requests: MistakeReviewClockTimingRequest[]) : Promise<Result<MistakeReviewClockTiming[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mistake_review_clock_timings", { file, requests }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scoreMistakeReviewMove(request: MistakeReviewMoveScoreRequest) : Promise<Result<MistakeReviewMoveScore, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("score_mistake_review_move", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMistakeReviewSampleLine(request: MistakeReviewSampleLineRequest) : Promise<Result<MistakeReviewSampleLine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mistake_review_sample_line", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMistakeReviewScanPaused(id: string, paused: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mistake_review_scan_paused", { id, paused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAnalysis(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_analysis", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopInteractiveEngines() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_interactive_engines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopMatchingEngine(engine: string, tab: string, goMode: GoMode, options: EngineOptions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_matching_engine", { engine, tab, goMode, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killEngines(tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engines", { tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEngineLogs(engine: string, tab: string) : Promise<Result<EngineLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_logs", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async askAiCoach(request: AiCoachRequest) : Promise<Result<AiCoachResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_ai_coach", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async askPlanCoach(request: PlanCoachRequest) : Promise<Result<PlanCoachResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_plan_coach", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readAiCoachSidecar(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_ai_coach_sidecar", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAiCoachSidecarRecord(path: string, recordKey: string, recordJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_ai_coach_sidecar_record", { path, recordKey, recordJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeAiCoachSidecarRecord(path: string, recordKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_ai_coach_sidecar_record", { path, recordKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memorySize() : Promise<number> {
    return await TAURI_INVOKE("memory_size");
},
async getPuzzle(file: string, minRating: number, maxRating: number, theme: string | null) : Promise<Result<Puzzle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle", { file, minRating, maxRating, theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleProgress(file: string) : Promise<Result<PuzzleProgressSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_progress", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlindfoldPuzzleProgress(file: string) : Promise<Result<PuzzleProgressSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blindfold_puzzle_progress", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrainingPuzzle(file: string, mode: PuzzleTrainingMode, minRating: number, maxRating: number, theme: string | null) : Promise<Result<PuzzleTrainingCandidate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_training_puzzle", { file, mode, minRating, maxRating, theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlindfoldTrainingPuzzle(file: string, mode: PuzzleTrainingMode, minRating: number, maxRating: number, theme: string | null) : Promise<Result<PuzzleTrainingCandidate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blindfold_training_puzzle", { file, mode, minRating, maxRating, theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordPuzzleAttempt(file: string, input: PuzzleAttemptInput) : Promise<Result<PuzzleAttemptResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_puzzle_attempt", { file, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordBlindfoldPuzzleAttempt(file: string, input: PuzzleAttemptInput) : Promise<Result<PuzzleAttemptResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_blindfold_puzzle_attempt", { file, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleDashboard(file: string, days: number | null) : Promise<Result<PuzzleDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_dashboard", { file, days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlindfoldPuzzleDashboard(file: string, days: number | null) : Promise<Result<PuzzleDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blindfold_puzzle_dashboard", { file, days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetPuzzleProgress(file: string) : Promise<Result<PuzzleProgressSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_puzzle_progress", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBlindfoldPuzzleProgress(file: string) : Promise<Result<PuzzleProgressSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_blindfold_puzzle_progress", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportPuzzleProgress(file: string, targetFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_puzzle_progress", { file, targetFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportBlindfoldPuzzleProgress(file: string, targetFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_blindfold_puzzle_progress", { file, targetFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchOpeningName(query: string) : Promise<Result<OutOpening[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_opening_name", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromFen(fen: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_fen", { fen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromFens(fens: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_fens", { fens }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromName(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayersGameInfo(file: string, id: number) : Promise<Result<PlayerGameInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players_game_info", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEngineConfig(path: string) : Promise<Result<EngineConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_config", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileExists(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_exists", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileMetadata(path: string) : Promise<Result<FileMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergePlayers(file: string, player1: number, player2: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_players", { file, player1, player2 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async convertPgn(file: string, dbPath: string, timestamp: number | null, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert_pgn", { file, dbPath, timestamp, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceDatabaseFromPgn(file: string, dbPath: string, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_database_from_pgn", { file, dbPath, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayer(file: string, id: number) : Promise<Result<Player | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMostCommonPlayer(file: string) : Promise<Result<Player | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_most_common_player", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectOtbGames(request: OtbImportRequest) : Promise<Result<OtbImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collect_otb_games", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops outstanding source requests while allowing the collector to finalize
 * and return every deduplicated game already merged into the partial PGN.
 */
async cancelOtbGames(jobId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_otb_games", { jobId });
},
async countPgnGames(file: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_pgn_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readGames(file: string, start: number, end: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_games", { file, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async splitPgnToFiles(file: string, targetDir: string, fileType: string) : Promise<Result<PgnSplitReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("split_pgn_to_files", { file, targetDir, fileType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lexPgn(pgn: string) : Promise<Result<Token[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lex_pgn", { pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isBmi2Compatible() : Promise<boolean> {
    return await TAURI_INVOKE("is_bmi2_compatible");
},
async deleteGame(file: string, n: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { file, n }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDuplicatedGames(file: string) : Promise<Result<DuplicateGameCleanupReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_duplicated_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatabaseClockCoverage(file: string) : Promise<Result<DatabaseClockCoverage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_clock_coverage", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEmptyGames(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_empty_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearGames() : Promise<void> {
    await TAURI_INVOKE("clear_games");
},
async setFileAsExecutable(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_file_as_executable", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editDbInfo(file: string, title: string | null, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_db_info", { file, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDbGame(file: string, gameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_db_game", { file, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeDbGame(file: string, gameId: number, pgn: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_db_game", { file, gameId, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveDatabase(file: string, newFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_database", { file, newFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportToPgn(file: string, destFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_to_pgn", { file, destFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authenticate(username: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authenticate", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeGame(filePath: string, n: number, pgn: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_game", { filePath, n, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadFile(id: string, url: string, path: string, token: string | null, finalize: boolean | null, totalSize: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_file", { id, url, path, token, finalize, totalSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTournaments(file: string, query: TournamentQuery) : Promise<Result<QueryResponse<Event[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournaments", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbInfo(file: string) : Promise<Result<DatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGames(file: string, query: GameQuery) : Promise<Result<QueryResponse<NormalizedGame[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_games", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findRepertoireGaps(request: RepertoireGapRequest) : Promise<Result<RepertoireGapReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_repertoire_gaps", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningHealthPlayerPositions(request: OpeningHealthPlayerPositionsRequest) : Promise<Result<OpeningHealthPlayerPositionsReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_health_player_positions", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDatabaseSearch(id: string) : Promise<void> {
    await TAURI_INVOKE("cancel_database_search", { id });
},
async setDatabaseSearchPaused(id: string, paused: boolean) : Promise<void> {
    await TAURI_INVOKE("set_database_search_paused", { id, paused });
},
async getPlanExplorer(file: string, query: GameQuery, maxPlies: number, requestId: string) : Promise<Result<PlanExplorerData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_plan_explorer", { file, query, maxPlies, requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPosition(file: string, query: GameQuery, tabId: string) : Promise<Result<[PositionStats[], NormalizedGame[]], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_position", { file, query, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayers(file: string, query: PlayerQuery) : Promise<Result<QueryResponse<Player[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleDbInfo(file: string) : Promise<Result<PuzzleDatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleThemes(file: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_themes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThemesForPuzzle(file: string, puzzleId: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_themes_for_puzzle", { file, puzzleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePuzzleDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_puzzle_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startGame(gameId: string, config: GameConfig) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_game", { gameId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameState(gameId: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_state", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async makeGameMove(gameId: string, uci: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("make_game_move", { gameId, uci }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takeBackGameMove(gameId: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_back_game_move", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resignGame(gameId: string, color: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resign_game", { gameId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortGame(gameId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_game", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameEngineLogs(gameId: string, color: string) : Promise<Result<EngineLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_engine_logs", { gameId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async preloadReferenceDb(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preload_reference_db", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProgress(id: string) : Promise<ProgressItem | null> {
    return await TAURI_INVOKE("get_progress", { id });
},
async clearProgress(id: string) : Promise<void> {
    await TAURI_INVOKE("clear_progress", { id });
},
async getSoundServerPort() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sound_server_port") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
bestMovesPayload: BestMovesPayload,
clockUpdateEvent: ClockUpdateEvent,
databaseProgress: DatabaseProgress,
gameMoveEvent: GameMoveEvent,
gameOverEvent: GameOverEvent,
localEvalBuildProgress: LocalEvalBuildProgress,
mistakeReviewScanProgress: MistakeReviewScanProgress,
otbImportProgress: OtbImportProgress,
progressEvent: ProgressEvent
}>({
bestMovesPayload: "best-moves-payload",
clockUpdateEvent: "clock-update-event",
databaseProgress: "database-progress",
gameMoveEvent: "game-move-event",
gameOverEvent: "game-over-event",
localEvalBuildProgress: "local-eval-build-progress",
mistakeReviewScanProgress: "mistake-review-scan-progress",
otbImportProgress: "otb-import-progress",
progressEvent: "progress-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AiCoachRequest = { requestId?: string; fen: string; sideToMove: string; playerColor?: string; moveHistory: string[]; pgn: string | null; pgnScope?: string; currentLinePgn?: string | null; wholeGamePgn?: string | null; gameAnalysis?: CoachGameAnalysisPoint[]; selectedMove: string | null; question: string; chatHistory?: CoachChatMessage[]; referenceContext?: CoachReferenceContext[]; existingLines: CoachEngineLine[]; existingLinesSource?: string; priorTargetedResults?: CoachTargetedResult[]; openingContext: CoachOpeningContext | null; openingContextError: string | null; enginePath: string; settings: AiCoachSettings }
export type AiCoachResponse = { answer: string; overview: string; categories: CoachCategory[]; analysisCoverage: CoachAnalysisCoverage | null; pgnScope: string; model: string; reasoningEffort?: string; usedExistingAnalysis: boolean; stockfishLines: CoachEngineLine[]; targetedResults: CoachTargetedResult[]; bookPassages: CoachBookPassage[]; bookCorpusAvailable: boolean }
export type AiCoachSettings = { enabled: boolean; geminiCommand: string; geminiModel: string; plannerModel?: string; reasoningEffort?: string; multipv: number; timeoutSecs: number }
export type AnalysisOptions = { fen: string; moves: string[]; annotateNovelties: boolean; referenceDb: string | null; reversed: boolean }
export type BestMoveSource = "lichess" | "chessdb"
export type BestMoves = { nodes: number; depth: number; score: Score; source?: BestMoveSource | null; uciMoves: string[]; sanMoves: string[]; multipv: number; nps: number }
export type BestMovesPayload = { bestLines: BestMoves[]; engine: string; tab: string; fen: string; moves: string[]; progress: number }
export type ClockUpdateEvent = { gameId: string; whiteTime: bigint | null; blackTime: bigint | null }
export type CoachAnalysisCoverage = { totalPositions: number; uniquePositions: number; cloudHits: number; liveAnalyses: number; failed: number; liveDepth: number; skippedPositions?: number; stoppedAtCloudBoundary?: boolean; boundaryPly?: number | null; complete?: boolean }
export type CoachBookLine = { lineId: string; lineKind: string; pgn: string; citation: string; matchedGamePly: number; matchedBookMoveIndex: number; matchedBookPly: number; playedSan: string; playedUci: string; bookMoveSan: string; bookMoveUci: string; playedMoveMatched: boolean; sharedPlies: number; moves: CoachBookLineMove[] }
export type CoachBookLineMove = { moveIndex: number; ply: number; san: string; uci: string; fenBefore: string; fenAfter: string; sourcePdfPage: number; sourcePrintedPage: number | null; sourceChunkId: string | null; confidence: number }
export type CoachBookPassage = { chunkId: string; bookId: string; title: string; author: string; shelf: string; chapterTitle: string; citation: string; pdfPageStart: number; pdfPageEnd: number; printedPageStart: number | null; printedPageEnd: number | null; excerpt: string; localPath: string; openingLines?: CoachBookLine[] }
export type CoachCategory = { id: string; label: string; summary: string; explanation: string; positions: CoachCategoryPosition[]; bookReferences: CoachCategoryBookReference[] }
export type CoachCategoryBookReference = { chunkId: string; whyItMatters: string; positionPly: number | null }
export type CoachCategoryPosition = { ply: number; san: string; title: string; explanation: string; engineEvidence: string; betterPlan: string }
export type CoachChatMessage = { role: string; content: string }
export type CoachEngineLine = { multipv: number; depth: number; eval: string; uciMoves: string[]; sanMoves: string[] }
export type CoachGameAnalysisPoint = { ply: number; move: string; beforeFen?: string | null; fen: string; playedUci?: string | null; playedSide?: string | null; eval: string | null; depth: number | null; annotations: string[] }
export type CoachOpeningContext = { source: string; fen: string; side: string; totalGames: number; filters: string; moves: CoachOpeningMove[] }
export type CoachOpeningMove = { san: string; uci: string; games: number; white: number; draw: number; black: number; usagePct: number; sideScorePct: number; blendedStrength: number; blendedLabel: string; databaseStrengthPct: number | null; engineCpLoss: number | null; engineRank: number | null; engineScore: string | null; notes: string[] }
export type CoachReferenceContext = { label: string; fen: string; ply: number; sanLine?: string[]; source?: string; detail?: string }
export type CoachTargetedResult = { requestType: string; reason: string; fen: string; moves: string[]; label: string; lines: CoachEngineLine[] }
export type DatabaseClockCoverage = { gameCount: number; gamesWithTiming: number }
export type DatabaseInfo = { title: string; description: string; player_count: number; event_count: number; game_count: number; storage_size: bigint; filename: string; indexed: boolean }
export type DatabaseProgress = { id: string; progress: number }
export type DrawReason = "stalemate" | "insufficientMaterial" | "threefoldRepetition" | "fiftyMoveRule" | "agreement"
export type DuplicateGameCleanupReport = { deletedGames: number; enrichedGames: number }
export type EngineConfig = { name: string; options: UciOptionConfig[] }
export type EngineLog = { type: "gui"; value: string } | { type: "engine"; value: string }
export type EngineMoveDelay = { minMs: number; maxMs: number; fideElo?: number | null; strengthElo?: number | null; initialTimeMs?: number | null; incrementMs?: number | null; useAsMoveTime?: boolean }
export type EngineOption = { name: string; value: string }
export type EngineOptions = { fen: string; moves: string[]; extraOptions: EngineOption[] }
export type Event = { id: number; name: string | null }
export type FileMetadata = { last_modified: number }
export type GameConfig = { white: PlayerConfig; black: PlayerConfig; whiteTimeControl: TimeControl | null; blackTimeControl: TimeControl | null; initialFen: string | null; initialMoves?: string[]; openingBook: OpeningBookConfig | null }
export type GameEndReason = "checkmate" | "timeout" | "resignation" | "abandonment"
export type GameMove = { uci: string; san: string; fenAfter: string; clock: bigint | null; whiteTime: bigint | null; blackTime: bigint | null }
export type GameMoveEvent = { gameId: string; moves: GameMove[]; fen: string; whiteTime: bigint | null; blackTime: bigint | null }
export type GameOutcome = "Won" | "Drawn" | "Lost"
export type GameOverEvent = { gameId: string; result: GameResult; moves: GameMove[] }
export type GameQuery = { options?: QueryOptions<GameSort> | null; player1?: number | null; player2?: number | null; tournament_id?: number | null; start_date?: string | null; end_date?: string | null; range1?: [number, number] | null; range2?: [number, number] | null; sides?: Sides | null; outcome?: string | null; position?: PositionQueryJs | null; wanted_result?: string | null }
export type GameResult = { type: "whiteWins"; reason: GameEndReason } | { type: "blackWins"; reason: GameEndReason } | { type: "draw"; reason: DrawReason }
export type GameSort = "id" | "date" | "whiteElo" | "blackElo" | "ply_count"
export type GameState = { gameId: string; status: GameStatus; initialFen: string; moves: GameMove[]; currentFen: string; ply: number; turn: string; whiteTime: bigint | null; blackTime: bigint | null; whitePlayer: string; blackPlayer: string }
export type GameStatus = "playing" | { finished: { result: GameResult } }
export type GoMode = { t: "PlayersTime"; c: PlayersTime } | { t: "Depth"; c: number } | { t: "Time"; c: number } | { t: "Nodes"; c: number } | { t: "Infinite" }
export type LocalEvalBuildProgress = { id: string; phase: string; progress: number; positions: bigint; skipped: bigint; compressedBytesRead: bigint; compressedBytesTotal: bigint | null; finished: boolean }
export type LocalEvalBuildReport = { outputDir: string; source: string; positions: bigint; skipped: bigint; shardCount: number; maxPvs: number; storageBytes: bigint; builtAt: bigint }
export type LocalEvalBuildRequest = { id: string | null; source: string | null; sourceUrl: string | null; outputDir: string | null; maxPvs: number | null; shardCount: number | null }
export type LocalEvalDbStatus = { available: boolean; path: string; positions: bigint; shardCount: number; maxPvs: number; storageBytes: bigint; builtAt?: bigint | null; source?: string | null; error?: string | null }
export type LocalLichessCloudEval = { fen: string; knodes: number; depth: number; pvs: LocalLichessCloudPv[] }
export type LocalLichessCloudPv = { moves: string; cp?: number | null; mate?: number | null }
export type MistakeReviewAnalysisMode = "single" | "layered"
export type MistakeReviewAttemptLabel = "best" | "good" | "okay" | "inaccuracy" | "mistake" | "blunder"
export type MistakeReviewClockTiming = { reviewKey: string; gameId: number; ply: number; moveSequence: string; moveTimeSeconds: number | null; clockBeforeSeconds: number | null; clockAfterSeconds: number | null; date: string | null; time: string | null; timeControl: string | null }
export type MistakeReviewClockTimingRequest = { reviewKey: string; fen: string; playedMoveUci: string; gameIds: number[] }
export type MistakeReviewGameMetadata = { gameId: number; date: string | null; time: string | null; openingName: string | null }
export type MistakeReviewMoveScore = { label: MistakeReviewAttemptLabel; passed: boolean; bestMoveSan: string; bestMoveUci: string; playedMoveSan: string; playedMoveUci: string; cpLoss: number; winProbabilityDrop: number; cpBefore: number; cpAfter: number; requestedDepth: number; reachedDepth: number; engineName: string }
export type MistakeReviewMoveScoreRequest = { requestId: string | null; fen: string; playedMoveUci: string; enginePath: string; engineName: string | null; depth: number | null; multiPv: number | null; thresholds: MistakeReviewThresholds | null }
export type MistakeReviewSampleLine = { moves: string[]; requestedDepth: number; reachedDepth: number; engineName: string }
export type MistakeReviewSampleLineRequest = { requestId: string | null; fen: string; firstMoveUci: string; enginePath: string; engineName: string | null; depth: number | null; maxPlies: number | null }
export type MistakeReviewScanProgress = { id: string; progress: number; gamesAnalyzed: number; gamesTotal: number; positionsAnalyzed: number; candidateMoves: number; mistakesFound: number; phase: string; paused: boolean; finished: boolean }
export type MistakeReviewScanReport = { gamesScanned: number; candidateMoves: number; positionsAnalyzed: number; lastAnalyzedGameId: number | null; stopped: boolean; mistakes: MistakeReviewScanResult[] }
export type MistakeReviewScanRequest = { requestId: string | null; playerDb: string; playerId: number; playerName: string | null; enginePath: string; engineName: string | null; analysisMode: MistakeReviewAnalysisMode | null; fastDepth: number | null; deepDepth: number | null; multiPv: number | null; thresholds: MistakeReviewThresholds | null; includeSeverities: MistakeReviewSeverityFilter | null; minWinProbabilityDrop: number | null; timeManagement: MistakeReviewTimeManagementSettings | null; timeControls: string[] | null; startDate: string | null; endDate: string | null; sinceGameId: number | null; maxGames: number | null }
export type MistakeReviewScanResult = { reviewKey: string; fen: string; normalizedFen: string; sideToMove: string; playerColor: string; moveSequence: string; playedMoveSan: string; playedMoveUci: string; bestMoveSan: string; bestMoveUci: string; pvSan: string[]; pvUci: string[]; refutationSan: string[]; refutationUci: string[]; severity: MistakeReviewSeverity; cpLoss: number; winProbabilityDrop: number; cpBefore: number; cpAfter: number; requestedDepth: number; reachedDepth: number; analysisMode: MistakeReviewAnalysisMode; fastDepth: number; multiPv: number; engineName: string; gameId: number; lastGameId: number; ply: number; moveNumber: number; date: string | null; time: string | null; openingName: string | null; opponent: string; timeControl: string | null; whiteName: string; blackName: string; whiteElo: number | null; blackElo: number | null; gameResult: string | null; moveTimeSeconds: number | null; clockBeforeSeconds: number | null; clockAfterSeconds: number | null; longThinkThresholdSeconds: number | null; occurrenceCount: number; gameIds: number[] }
export type MistakeReviewSeverity = "inaccuracy" | "mistake" | "blunder"
export type MistakeReviewSeverityFilter = { inaccuracy: boolean; mistake: boolean; blunder: boolean }
export type MistakeReviewThresholds = { inaccuracy: number; mistake: number; blunder: number }
export type MistakeReviewTimeManagementSettings = { enabled: boolean; minMoveSeconds: number }
export type MoveAnalysis = { best: BestMoves[]; novelty: boolean; is_sacrifice: boolean }
export type NormalizedGame = { id: number; fen: string; event: string; event_id: number; site: string; site_id: number; date?: string | null; time?: string | null; round?: string | null; white: string; white_id: number; white_elo?: number | null; black: string; black_id: number; black_elo?: number | null; result: Outcome; time_control?: string | null; eco?: string | null; ply_count?: number | null; moves: string }
export type OpeningBookConfig = { path: string; maxPly?: bigint }
export type OpeningHealthPlayerPosition = { fen: string; normalizedFen: string; ply: number; sideToMove: string; moveSequence: string; playerMoveSan: string; playerMoveUci: string; playerGames: number; playerPositionGames: number; playerWhite: number; playerDraw: number; playerBlack: number; playerScore: number; lastPlayed: string | null; sampleGameIds: number[] }
export type OpeningHealthPlayerPositionsReport = { playerGames: number; candidatePositions: number; positions: OpeningHealthPlayerPosition[] }
export type OpeningHealthPlayerPositionsRequest = { playerDb: string; playerId: number | null; color: string; maxPlies: number; startDate: string | null; endDate: string | null; requestId: string }
export type OtbImportNewestGame = { date: string; event: string; white: string; black: string; result: string; source: string }
export type OtbImportProgress = { jobId: string; source: string; phase: string; current: number; total: number; gamesFound: number; message: string }
export type OtbImportReport = { playerName: string; fideId: string | null; outputPath: string; cancelled: boolean; gamesFound: number; duplicatesRemoved: number; suspectedOnlineGamesExcluded: number; identityMismatchesExcluded: number; newestGame: OtbImportNewestGame | null; sources: OtbImportSourceReport[] }
export type OtbImportRequest = { jobId: string; playerName: string; fideId: string | null; fromYear: number; includeLichessBroadcasts: boolean; includeChessResults: boolean; includeChessbaseNews: boolean; includeOfficialPgnIndexes: boolean; includeTwic: boolean; localPgnPaths: string[]; cacheDir: string; outputPath: string }
export type OtbImportSourceReport = { source: string; archivesChecked: number; cachedArchives: number; matchedGames: number; uniqueGamesAdded: number; errors: string[] }
export type OutOpening = { name: string; fen: string }
export type Outcome = "1-0" | "0-1" | "1/2-1/2" | "*"
export type PgnSplitReport = { created: number; targetDir: string }
export type PlanCoachRequest = { fen: string; sideToMove: string; surface: string; subjectKind: string; title: string; summary: string; planLines?: string[]; stats?: string[]; evidence?: string[]; settings: PlanCoachSettings }
export type PlanCoachResponse = { answer: string; model: string }
export type PlanCoachSettings = { enabled: boolean; geminiCommand: string; geminiModel?: string; timeoutSecs: number }
export type PlanExplorerData = { fen: string; total_games: number; sampled_games: number; max_plies: number; pieces: PlanExplorerPiece[]; setups: PlanExplorerSetup[] }
export type PlanExplorerLine = { squares: string[]; san: string[]; uci: string[]; games: number; white: number; draw: number; black: number }
export type PlanExplorerPiece = { color: string; role: string; from: string; total: number; lines: PlanExplorerLine[] }
export type PlanExplorerSetup = { plans: PlanExplorerSetupPlan[]; games: number; white: number; draw: number; black: number }
export type PlanExplorerSetupPlan = { color: string; role: string; from: string; line: PlanExplorerLine }
export type Player = { id: number; name: string | null; elo: number | null }
export type PlayerConfig = { type: "human"; name: string } | { type: "engine"; name: string; path: string; options?: EngineOption[]; go: GoMode | null; useClockTimeManagement?: boolean; moveDelay?: EngineMoveDelay | null }
export type PlayerGameInfo = { site_stats_data: SiteStatsData[] }
export type PlayerQuery = { options: QueryOptions<PlayerSort>; name?: string | null; range?: [number, number] | null }
export type PlayerSort = "id" | "name" | "elo"
export type PlayersTime = { white: number; black: number; winc: number; binc: number }
export type PositionQueryJs = { fen: string; type_: string }
export type PositionStats = { move: string; white: number; draw: number; black: number; lastPlayed: string | null }
export type ProgressEvent = { id: string; progress: number; finished: boolean }
export type ProgressItem = { id: string; progress: number; finished: boolean }
export type Puzzle = { id: number; fen: string; moves: string; rating: number; rating_deviation: number; popularity: number; nb_plays: number }
export type PuzzleAttemptInput = { puzzleId: number; mode: PuzzleTrainingMode; outcome: PuzzleAttemptOutcome; timeSpentMs: bigint; usedHint: boolean; viewedSolution: boolean; wrongMoves: bigint }
export type PuzzleAttemptOutcome = "correct" | "incorrect"
export type PuzzleAttemptQuality = "failed" | "assisted" | "hard" | "solid" | "fluent"
export type PuzzleAttemptResult = { summary: PuzzleProgressSummary; card: PuzzleCardProgress; themes: string[]; eloBefore: number; eloAfter: number; eloDelta: number; attemptQuality: PuzzleAttemptQuality; themeDeltas: PuzzleThemeDelta[] }
export type PuzzleCardProgress = { puzzleId: number; dueAt: bigint; state: PuzzleSrsState; reps: bigint; lapses: bigint; intervalDays: number; ease: number; lastAttemptAt: bigint | null; totalAttempts: bigint; correctAttempts: bigint; lastQuality: PuzzleAttemptQuality; mastered: boolean }
export type PuzzleDashboard = { summary: PuzzleProgressSummary; themes: PuzzleThemeStatsRow[]; trends: PuzzleTrendPoint[]; srsCounts: PuzzleSrsCounts; dueCards: PuzzleSrsQueueRow[] }
export type PuzzleDatabaseInfo = { title: string; description: string; puzzleCount: number; storageSize: bigint; path: string }
export type PuzzleProgressSummary = { dbKey: string; puzzleElo: number; totalAttempts: bigint; correctAttempts: bigint; accuracy: number; due: bigint; learning: bigint; review: bigint; mastered: bigint; themesTracked: bigint; updatedAt: bigint }
export type PuzzleSrsCounts = { learning: bigint; relearning: bigint; review: bigint; mastered: bigint; due: bigint }
export type PuzzleSrsQueueRow = { puzzleId: number; rating: number; themes: string[]; dueAt: bigint; state: PuzzleSrsState; reps: bigint; lapses: bigint; intervalDays: number; totalAttempts: bigint; correctAttempts: bigint; lastQuality: PuzzleAttemptQuality; mastered: boolean }
export type PuzzleSrsState = "new" | "learning" | "relearning" | "review" | "mastered"
export type PuzzleThemeDelta = { theme: string; skillBefore: number; skillAfter: number; skillDelta: number }
export type PuzzleThemeStatsRow = { theme: string; attempts: bigint; correct: bigint; accuracy: number; averageTimeMs: number; skill: number; weaknessScore: number; recentAttempts: bigint; recentAccuracy: number; due: bigint; mastered: bigint; lastAttemptAt: bigint | null }
export type PuzzleTrainingCandidate = { puzzle: Puzzle; themes: string[]; mode: PuzzleTrainingMode; reason: string; dbKey: string; progress: PuzzleCardProgress | null }
export type PuzzleTrainingMode = "coach" | "srsReview" | "themeFocus" | "ratingLadder" | "random"
export type PuzzleTrendPoint = { dateKey: string; puzzleElo: number; attempts: bigint; accuracy: number; solved: bigint; due: bigint; mastered: bigint }
export type QueryOptions<SortT> = { skipCount: boolean; page?: number | null; pageSize?: number | null; sort: SortT; direction: SortDirection }
export type QueryResponse<T> = { data: T; count: number | null }
export type RepertoireGap = { fen: string; normalizedFen: string; ply: number; sideToMove: string; moveSequence: string; playerMoveSan: string; playerMoveUci: string; playerGames: number; playerPositionGames: number; playerWhite: number; playerDraw: number; playerBlack: number; playerScore: number; lastPlayed: string | null; referenceGames: number; referenceMoveRank: number | null; referenceMoveShare: number; referenceScore: number | null; topReferenceMoveScore: number | null; classification: RepertoireGapClassification; popularityGap: number; scoreGap: number; severity: number; sampleGameIds: number[]; topReferenceMoves: RepertoireGapReferenceMove[] }
export type RepertoireGapClassification = "repertoireGap" | "preparedUnderperforming" | "lowConfidence"
export type RepertoireGapReferenceMove = { san: string; uci: string; games: number; white: number; draw: number; black: number; share: number; scoreForSide: number }
export type RepertoireGapReport = { playerGames: number; candidatePositions: number; referencePositions: number; gaps: RepertoireGap[] }
export type RepertoireGapRequest = { playerDb: string; referenceDb: string; playerId: number | null; color: string; maxPlies: number; minPlayerGames: number; minReferenceGames: number; topReferenceMoves: number; startDate: string | null; endDate: string | null; requestId: string }
export type Score = { value: ScoreValue; 
/**
 * The probability of each result (win, draw, loss).
 */
wdl: [number, number, number] | null }
export type ScoreValue = 
/**
 * The score in centipawns.
 */
{ type: "cp"; value: number } | 
/**
 * Mate coming up in this many moves. Negative value means the engine is getting mated.
 */
{ type: "mate"; value: number }
export type Sides = "BlackWhite" | "WhiteBlack" | "Any"
export type SiteStatsData = { site: string; player: string; data: StatsData[] }
export type SortDirection = "asc" | "desc"
export type StatsData = { date: string; is_player_white: boolean; player_elo: number; result: GameOutcome; time_control: string; opening: string }
export type TimeControl = { initialTime: bigint; increment: bigint }
export type Token = { type: "ParenOpen" } | { type: "ParenClose" } | { type: "Comment"; value: string } | { type: "San"; value: string } | { type: "Header"; value: { tag: string; value: string } } | { type: "Nag"; value: string } | { type: "Outcome"; value: string }
export type TournamentQuery = { options: QueryOptions<TournamentSort>; name: string | null }
export type TournamentSort = "id" | "name"
/**
 * Represents a UCI option definition.
 */
export type UciOptionConfig = 
/**
 * The option of type `check` (a boolean).
 */
{ type: "check"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this `bool` property.
 */
default: boolean | null } } | 
/**
 * The option of type `spin` (a signed integer).
 */
{ type: "spin"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this integer property.
 */
default: bigint | null; 
/**
 * The minimal value of this integer property.
 */
min: bigint | null; 
/**
 * The maximal value of this integer property.
 */
max: bigint | null } } | 
/**
 * The option of type `combo` (a list of strings).
 */
{ type: "combo"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value for this list of strings.
 */
default: string | null; 
/**
 * The list of acceptable strings.
 */
var: string[] } } | 
/**
 * The option of type `button` (an action).
 */
{ type: "button"; value: { 
/**
 * The name of the option.
 */
name: string } } | 
/**
 * The option of type `string` (a string, unsurprisingly).
 */
{ type: "string"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this string option.
 */
default: string | null } }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
