import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { desktopApi, type DataPackEntry, type DataPackStatus, type OtbLibraryStatus } from "@/features/tournaments/platform";
import { addOtbUpdates, otbEntries, otbMissingEntries, prepareOtbLibrary, setOtbPreferences, startOtbDownloadManager, startOtbDownload, useOtbDownloads } from "../otbDownloads";
vi.mock("@/features/tournaments/platform", () => ({ isDesktop: () => true, desktopApi: { dataPackStatus: vi.fn(), otbLibraryStatus: vi.fn(), maintainOtbLibrary: vi.fn(), setOtbLibraryPreferences: vi.fn(), settingsGet: vi.fn(), settingsSet: vi.fn(), checkOtbPackUpdates: vi.fn(), reviewDataPack: vi.fn(), startDataPack: vi.fn(), activateDataPack: vi.fn() } }));
const base: DataPackEntry = { id:"otb-2026-07-v1",kind:"otb",title:"OTB search database",summary:"Lichess broadcasts",detail:"",periodStart:"2020-01",periodEnd:"2026-07",downloadBytes:100,installedBytes:200,manifestSha256:"a".repeat(64) };
const next = { ...base,id:"otb-2026-08-v1",periodStart:"2026-08",periodEnd:"2026-08" };
let status: DataPackStatus, saved: Map<string,string>, stop: (()=>void)|undefined;
let library: OtbLibraryStatus;
const baseMonths=Array.from({length:79},(_,i)=>`${2020+Math.floor(i/12)}-${String(i%12+1).padStart(2,"0")}`);
beforeEach(() => {
 vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-10T12:00:00Z')); vi.clearAllMocks(); saved=new Map([["otb.download.lastCheck",String(Date.now())]]);
 status={catalog:[base],jobs:[],defaultParent:"D:/data",selectedIds:[],openingPackSelected:false,sharedOpeningsAvailable:false};
 library={managed:false,downloaded:false,enabled:false,keepYears:null,months:[],bytes:0,parent:"D:/data",importedIds:[],pendingIds:[],maintenanceNeeded:false};
 useOtbDownloads.setState({snapshot:null,library:null,error:"",statusError:"",automatic:false,checking:false,managing:false,operation:null});
 vi.mocked(desktopApi.otbLibraryStatus).mockImplementation(async()=>structuredClone(library));
 vi.mocked(desktopApi.setOtbLibraryPreferences).mockImplementation(async(years,enabled)=>{library.managed=true;library.keepYears=years;library.enabled=enabled;});
 vi.mocked(desktopApi.maintainOtbLibrary).mockImplementation(async()=>{library.months.push("2026-08");library.maintenanceNeeded=false;library.pendingIds=[];});
 vi.mocked(desktopApi.dataPackStatus).mockImplementation(async()=>structuredClone(status));
 vi.mocked(desktopApi.settingsGet).mockImplementation(async key=>saved.get(key)??null);
 vi.mocked(desktopApi.settingsSet).mockImplementation(async(key,value)=>{saved.set(key,value);});
 vi.mocked(desktopApi.checkOtbPackUpdates).mockResolvedValue(0);
 vi.mocked(desktopApi.activateDataPack).mockImplementation(async id=>{status.selectedIds.push(id);});
 vi.mocked(desktopApi.reviewDataPack).mockResolvedValue({token:"review",id:next.id,parent:"D:/data",path:"D:/data/month/data",downloadBytes:100,installedBytes:200,requiredBytes:500,availableBytes:100000});
 vi.mocked(desktopApi.startDataPack).mockImplementation(async()=>{const job={id:next.id,state:"running" as const,parent:"D:/data",path:"D:/data/month/data",phase:"downloading",completedBytes:0,totalBytes:100,error:null,manifestSha256:next.manifestSha256};status.jobs.push(job);return job;});
});
afterEach(()=>{stop?.();stop=undefined;vi.useRealTimers();});
const baseReady=()=>{library.downloaded=true;library.months=[...baseMonths];library.bytes=200;status.jobs=[{id:base.id,state:"ready",parent:"D:/data",path:"D:/data/base/data",phase:"ready",completedBytes:100,totalBytes:100,error:null,manifestSha256:base.manifestSha256}];};
describe("OTB download lifecycle",()=>{
 it("freezes the exact removal and retained months through cleanup and readback",async()=>{
   baseReady();library.managed=true;library.months=["2021-09","2021-11","2023-09","2026-07"];
   useOtbDownloads.setState({snapshot:status,library});
   let finish!:()=>void;
   vi.mocked(desktopApi.setOtbLibraryPreferences).mockImplementation(()=>new Promise<void>(resolve=>finish=resolve));
   const work=setOtbPreferences(3,true,library.parent);
   expect(useOtbDownloads.getState().operation).toMatchObject({kind:"range",dates:{removing:["2021-09","2021-11"],keeping:["2023-09","2026-07"]}});
   library.months=["2023-09","2026-07"];
   expect(useOtbDownloads.getState().operation?.dates?.removing).toEqual(["2021-09","2021-11"]);
   finish();await work;
   expect(useOtbDownloads.getState()).toMatchObject({operation:null,managing:false});
 });
 it("keeps preparation visible until fresh status confirms the result",async()=>{
   baseReady();library.managed=true;library.maintenanceNeeded=true;
   useOtbDownloads.setState({snapshot:status,library});
   let finish!:()=>void, readback!:()=>void;
   vi.mocked(desktopApi.maintainOtbLibrary).mockImplementation(()=>new Promise<void>(resolve=>finish=resolve));
   vi.mocked(desktopApi.otbLibraryStatus).mockImplementation(()=>new Promise<OtbLibraryStatus>(resolve=>readback=()=>resolve({...library,maintenanceNeeded:false})));
   const work=prepareOtbLibrary();
   expect(useOtbDownloads.getState()).toMatchObject({managing:true,operation:{kind:"prepare",startedAt:Date.now()}});
   finish();await vi.advanceTimersByTimeAsync(1000);
   expect(useOtbDownloads.getState().managing).toBe(true);
   readback();await work;
   expect(useOtbDownloads.getState()).toMatchObject({managing:false,operation:null,library:{maintenanceNeeded:false}});
 });
 it("keeps failed work visible in shared state after the panel closes",async()=>{
   baseReady();library.managed=true;useOtbDownloads.setState({snapshot:status,library});
   vi.mocked(desktopApi.setOtbLibraryPreferences).mockRejectedValueOnce(Error("Drive disconnected"));
   await expect(setOtbPreferences(3,true,library.parent)).rejects.toThrow("Drive disconnected");
   expect(useOtbDownloads.getState()).toMatchObject({managing:false,operation:null,error:"Drive disconnected"});
 });
 it("never starts an initial multi-gigabyte download automatically",async()=>{saved.set("otb.download.autoMonthly","true");stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.startDataPack).not.toHaveBeenCalled();expect(desktopApi.checkOtbPackUpdates).not.toHaveBeenCalled();});
 it("checks new months for a restored collection without inventing download-job records",async()=>{library.downloaded=true;library.managed=true;library.months=[...baseMonths];saved.set("otb.download.lastCheck","0");stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.checkOtbPackUpdates).toHaveBeenCalledOnce();expect(desktopApi.startDataPack).not.toHaveBeenCalled();expect(status.jobs).toEqual([]);});
 it("preserves an unticked completed download after closing or restarting",async()=>{baseReady();stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.activateDataPack).not.toHaveBeenCalled();stop();stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.activateDataPack).not.toHaveBeenCalled();expect(status.selectedIds).toEqual([]);});
 it("checks monthly snapshots without downloading them when automatic downloads are off",async()=>{baseReady();status.selectedIds=[base.id];saved.set("otb.download.lastCheck","0");vi.mocked(desktopApi.checkOtbPackUpdates).mockImplementation(async()=>{status.catalog.push(next);return 1;});stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.checkOtbPackUpdates).toHaveBeenCalledOnce();expect(desktopApi.startDataPack).not.toHaveBeenCalled();});
 it("downloads a new month once and preserves cancellation across restart",async()=>{baseReady();status.selectedIds=[base.id];status.catalog.push(next);saved.set("otb.download.autoMonthly","true");stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(1);expect(desktopApi.startDataPack).toHaveBeenCalledOnce();status.jobs.at(-1)!.state="cancelled";stop();stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.startDataPack).toHaveBeenCalledOnce();});
 it("refuses an insufficient-space transfer before starting it",async()=>{vi.mocked(desktopApi.reviewDataPack).mockResolvedValue({...await desktopApi.reviewDataPack(next.id,"D:/data"),availableBytes:1});await expect(startOtbDownload(next,"D:/data")).rejects.toThrow("Not enough space");expect(desktopApi.startDataPack).not.toHaveBeenCalled();});
 it("keeps automatic monthly downloads in the customer's chosen data folder",async()=>{baseReady();status.defaultParent="C:/default";status.selectedIds=[base.id];status.catalog.push(next);saved.set("otb.download.autoMonthly","true");stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(1);expect(desktopApi.reviewDataPack).toHaveBeenCalledWith(next.id,"D:/data");});
 it("keeps opening/evaluation downloads out of OTB choices",()=>{status.catalog.push({...base,id:"rated",kind:"rated"});expect(otbEntries(status)).toEqual([base]);});
 it("does not redownload expired years in a rolling range, but offers them after widening",()=>{baseReady();library.keepYears=5;library.months=baseMonths.filter(m=>m>="2021-09");expect(otbMissingEntries(status,library)).toEqual([]);library.keepYears=null;expect(otbMissingEntries(status,library)).toEqual([base]);});
 it("adds completed monthly games while keeping the whole collection switched off",async()=>{baseReady();library.managed=true;library.enabled=false;library.maintenanceNeeded=true;library.pendingIds=[next.id];stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(1);expect(desktopApi.maintainOtbLibrary).toHaveBeenCalledOnce();expect(library.enabled).toBe(false);expect(desktopApi.activateDataPack).not.toHaveBeenCalled();});
 it("persists a manual update queue so the next month follows after the dialog closes",async()=>{baseReady();library.managed=true;status.catalog.push(next);useOtbDownloads.setState({snapshot:status,library});await addOtbUpdates("D:/data");expect(saved.get("otb.download.pendingUpdates")).toBe(JSON.stringify([next.id]));expect(desktopApi.startDataPack).toHaveBeenCalledOnce();});
 it("does not retry failed preparation silently",async()=>{baseReady();library.managed=true;library.maintenanceNeeded=true;saved.set("otb.download.autoError","Disk full");stop=startOtbDownloadManager();await vi.advanceTimersByTimeAsync(16000);expect(desktopApi.maintainOtbLibrary).not.toHaveBeenCalled();});
});
